#include "../battle_anims/core.h"

void Unused_AnimateMon_Slow_Normal(void);
void AnimateMon_Menu(uint8_t* hl);
void AnimateMon_Trade(uint8_t* hl);
void AnimateMon_Evolve(uint8_t* hl);
void AnimateMon_Hatch(uint8_t* hl);
void AnimateMon_HOF(uint8_t* hl);
// void PokeAnims(void);
void AnimateFrontpic(uint8_t* hl, uint8_t d, uint8_t e);
void AnimateBattleSceneFrontpic(enum BattleSceneBattlerId battler, uint8_t animation);
void LoadMonAnimation(uint8_t* hl, uint8_t d, uint8_t e);
bool SetUpPokeAnim(void);
// void PokeAnim_SetupCommands(void);
// void PokeAnim_SetWait(void);
// void PokeAnim_Wait(void);
// void PokeAnim_Setup(void);
// void PokeAnim_Setup2(void);
// void PokeAnim_Idle(void);
// void PokeAnim_Play(void);
// void PokeAnim_Play2(void);
// void PokeAnim_BasePic(void);
// void PokeAnim_Finish(void);
// void PokeAnim_Cry(void);
// void PokeAnim_CryNoWait(void);
// void PokeAnim_StereoCry(void);
// void PokeAnim_DeinitFrames(void);
// bool AnimateMon_CheckIfPokemon(void);
// void PokeAnim_InitPicAttributes(const uint8_t* bc, uint8_t* hl, uint8_t d);
// void PokeAnim_InitAnim(uint8_t b, uint8_t c);
// void PokeAnim_DoAnimScript(void);
// void PokeAnim_End(void);
// uint8_t PokeAnim_GetDuration(uint8_t a);
// void PokeAnim_GetFrame(void);
// void PokeAnim_StartWaitAnim(void);
// void PokeAnim_StopWaitAnim(void);
// bool PokeAnim_IsUnown(species_t a);
// bool PokeAnim_IsEgg(void);
// void PokeAnim_GetPointer(void);
uint16_t PokeAnim_GetBitmaskIndex(void);
void PokeAnim_CopyBitmaskToBuffer(void);
void PokeAnim_ConvertAndApplyBitmask(void);
// void PokeAnim_PlaceGraphic(void);
// void PokeAnim_SetVBank1(void);
// void PokeAnim_SetVBank0(void);
// uint8_t* PokeAnim_GetAttrmapCoord(void);
// void GetMonAnimPointer(void);
// uint8_t PokeAnim_GetFrontpicDims(void);
void GetMonFramesPointer(void);
void GetMonBitmaskPointer(void);
// uint8_t PokeAnim_GetSpeciesOrUnown(species_t a);
void Unused_HOF_AnimateAlignedFrontpic(uint8_t* de, uint8_t c);
void HOF_AnimateFrontpic(uint8_t* de, uint8_t c);
