#include "wram.h"
#include <stddef.h>

struct wram_s* wram;
struct OptionsData gOptions;
struct CurMapData gCurMapData;
struct PokemonData gPokemon;
struct PlayerData gPlayer;
struct CrystalData gCrystal;
struct NativeUIState gNativeUI;

#include <stddef.h>

#define check_wram0_field(_fld)                         static_assert(offsetof(struct wram_s, _fld) == (_fld - WRAM_0_ADDR), "")
#define check_wramx_field(_fld, _bank)                  static_assert(offsetof(struct wram_s, _fld) - (0x1000 * (_bank)) == (_fld - WRAM_1_ADDR), "")

#define check_wram0_field_mapped(_fld, _wvar)           static_assert(offsetof(struct wram_s, _fld) == (_wvar - WRAM_0_ADDR), "")
#define check_wramx_field_mapped(_fld, _bank, _wvar)    static_assert(offsetof(struct wram_s, _fld) - (0x1000 * (_bank)) == (_wvar - WRAM_1_ADDR), "")

// bank 0
// section Stack
check_wram0_field(wStackBottom);
check_wram0_field(wStackTop);
// section Audio RAM
check_wram0_field(wMusicPlaying);
check_wram0_field_mapped(wChannel, wChannel1);
check_wram0_field(wCurTrackDuty);
check_wram0_field(wCurTrackVolumeEnvelope);
check_wram0_field(wCurTrackFrequency);
check_wram0_field(wUnusedBCDNumber);
check_wram0_field(wCurNoteDuration);
check_wram0_field(wCurMusicByte);
check_wram0_field(wCurChannel);
check_wram0_field(wVolume);
check_wram0_field(wSoundOutput);
check_wram0_field(wPitchSweep);
check_wram0_field(wMusicID);
check_wram0_field(wMusicBank);
check_wram0_field(wNoiseSampleAddress);
check_wram0_field(wNoiseSampleDelay);
check_wram0_field(wMusicNoiseSampleSet);
check_wram0_field(wSFXNoiseSampleSet);
check_wram0_field(wLowHealthAlarm);
check_wram0_field(wMusicFade);
check_wram0_field(wMusicFadeCount);
check_wram0_field(wMusicFadeID);
check_wram0_field(wCryPitch);
check_wram0_field(wCryLength);
check_wram0_field(wLastVolume);
check_wram0_field(wUnusedMusicF9Flag);
check_wram0_field(wSFXPriority);
check_wram0_field(wChannel1JumpCondition);
check_wram0_field(wChannel2JumpCondition);
check_wram0_field(wChannel3JumpCondition);
check_wram0_field(wChannel4JumpCondition);
check_wram0_field(wStereoPanningMask);
check_wram0_field(wCryTracks);
check_wram0_field(wSFXDuration);
check_wram0_field(wCurSFX);
check_wram0_field(wMapMusic);
check_wram0_field(wDontPlayMapMusicOnReload);
// section WRAM
check_wram0_field(wLZAddress);
check_wram0_field(wLZBank);
check_wram0_field(wBoxAlignment);
check_wram0_field_mapped(legacyInputRuntime, wInputType);
check_wram0_field(wDebugFlags);
check_wram0_field(wGameLogicPaused);
check_wram0_field(wSpriteUpdatesEnabled);
check_wram0_field(wUnusedScriptByte);
check_wram0_field(wMapTimeOfDay);
check_wram0_field(wPrinterConnectionOpen);
check_wram0_field(wPrinterOpcode);
check_wram0_field(wPrevDexEntry);
check_wram0_field(wDisableTextAcceleration);
check_wram0_field(wPrevLandmark);
check_wram0_field(wCurLandmark);
check_wram0_field(wLandmarkSignTimer);
check_wram0_field(wLinkMode);
check_wram0_field(wScriptVar);
check_wram0_field(wPlayerNextMovement);
check_wram0_field(wPlayerMovement);
check_wram0_field(wMovementObject);
check_wram0_field(wMovementDataBank);
check_wram0_field(wMovementDataAddress);
check_wram0_field(wIndexedMovement2Pointer);
check_wram0_field(wMovementByteWasControlSwitch);
check_wram0_field(wObjectPriorities);
check_wram0_field(wMovementPointer);
check_wram0_field(wTempObjectCopyMapObjectIndex);
check_wram0_field(wTempObjectCopySprite);
check_wram0_field(wTempObjectCopySpriteVTile);
check_wram0_field(wTempObjectCopyPalette);
check_wram0_field(wTempObjectCopyMovement);
check_wram0_field(wTempObjectCopyRange);
check_wram0_field(wTempObjectCopyX);
check_wram0_field(wTempObjectCopyY);
check_wram0_field(wTempObjectCopyRadius);
check_wram0_field(wTileDown);
check_wram0_field(wTileUp);
check_wram0_field(wTileLeft);
check_wram0_field(wTileRight);
check_wram0_field(wTilePermissions);
// section wSpriteAnims
check_wram0_field(wSpriteAnimDict);
check_wram0_field_mapped(wSpriteAnim, wSpriteAnim1);
check_wram0_field(wMobileErrorCodeBuffer);
check_wram0_field(wc303);
check_wram0_field(wc305);
check_wram0_field(wc306);
check_wram0_field(wc307);
check_wram0_field(wc308);
check_wram0_field(wc309);
check_wram0_field(wc30a);
check_wram0_field(wc30b);
check_wram0_field(wc30c);
check_wram0_field(wc30d);
check_wram0_field(wc30e);
check_wram0_field(wc30f);
check_wram0_field(wc310);
check_wram0_field(wc311);
check_wram0_field(wc312);
check_wram0_field(wc313);
check_wram0_field(wc314);
check_wram0_field(wc319);
check_wram0_field(wc31a);
check_wram0_field(wc31b);
check_wram0_field(wc31c);
check_wram0_field(wc31d);
check_wram0_field(wc31e);
check_wram0_field(wc31f);
check_wram0_field(wc320);
check_wram0_field(wc346);
check_wram0_field(wc3ac);
check_wram0_field(wSpriteAnimCount);
check_wram0_field(wCurSpriteOAMAddr);
check_wram0_field(wCurIcon);
check_wram0_field(wCurIconTile);
check_wram0_field(wSpriteAnimID);
check_wram0_field(wCurSpriteOAMFlags);
check_wram0_field(wSpriteAnimAddrBackup);
check_wram0_field(wCurAnimVTile);
check_wram0_field(wCurAnimXCoord);
check_wram0_field(wCurAnimYCoord);
check_wram0_field(wCurAnimXOffset);
check_wram0_field(wCurAnimYOffset);
check_wram0_field(wGlobalAnimYOffset);
check_wram0_field(wGlobalAnimXOffset);
check_wram0_field(wSpriteAnimDataEnd);
check_wram0_field(wc3cc);
check_wram0_field(wc3cd);
check_wram0_field(wc3ec);
check_wram0_field(wc3ed);
check_wram0_field(wc3ee);
check_wram0_field(wc3ef);
check_wram0_field(wc3f0);
check_wram0_field(wc3f1);
check_wram0_field(wc3f2);
check_wram0_field(wc3f3);
check_wram0_field(wc3f4);
check_wram0_field(wc3f5);
check_wram0_field(wc3f6);
check_wram0_field(wc3f7);
check_wram0_field(wc3f8);
check_wram0_field(wc3f9);
check_wram0_field(wc3fa);
check_wram0_field(wc3fb);
check_wram0_field(wc3fc);
// section Sprites
check_wram0_field_mapped(wVirtualOAMSprite, wVirtualOAMSprite00);
// section Tilemap
check_wram0_field(wTilemap);
// section Miscellaneous
check_wram0_field(wSurroundingTiles);
check_wram0_field(wBoxPartialData);
check_wram0_field(wBT_OTTemp);
check_wram0_field(wEnemyMoveStruct);
check_wram0_field(wPlayerMoveStruct);
check_wram0_field(wEnemyMonNickname);
check_wram0_field(wBattleMonNickname);
check_wram0_field(wBattleMon);
check_wram0_field(wWildMon);
check_wram0_field(wEnemyTrainerItem1);
check_wram0_field(wEnemyTrainerItem2);
check_wram0_field(wEnemyTrainerBaseReward);
check_wram0_field(wEnemyTrainerAIFlags);
check_wram0_field(wOTClassName);
check_wram0_field(wCurOTMon);
check_wram0_field(wBattleParticipantsNotFainted);
check_wram0_field(wTypeModifier);
check_wram0_field(wCriticalHit);
check_wram0_field(wAttackMissed);
check_wram0_field(wPlayerSubStatus1);
check_wram0_field(wPlayerSubStatus2);
check_wram0_field(wPlayerSubStatus3);
check_wram0_field(wPlayerSubStatus4);
check_wram0_field(wPlayerSubStatus5);
check_wram0_field(wEnemySubStatus1);
check_wram0_field(wEnemySubStatus2);
check_wram0_field(wEnemySubStatus3);
check_wram0_field(wEnemySubStatus4);
check_wram0_field(wEnemySubStatus5);
check_wram0_field(wPlayerRolloutCount);
check_wram0_field(wPlayerConfuseCount);
check_wram0_field(wPlayerToxicCount);
check_wram0_field(wPlayerDisableCount);
check_wram0_field(wPlayerEncoreCount);
check_wram0_field(wPlayerPerishCount);
check_wram0_field(wPlayerFuryCutterCount);
check_wram0_field(wPlayerProtectCount);
check_wram0_field(wEnemyRolloutCount);
check_wram0_field(wEnemyConfuseCount);
check_wram0_field(wEnemyToxicCount);
check_wram0_field(wEnemyDisableCount);
check_wram0_field(wEnemyEncoreCount);
check_wram0_field(wEnemyPerishCount);
check_wram0_field(wEnemyFuryCutterCount);
check_wram0_field(wEnemyProtectCount);
check_wram0_field(wPlayerDamageTaken);
check_wram0_field(wEnemyDamageTaken);
check_wram0_field(wBattleReward);
check_wram0_field(wBattleAnimParam);
check_wram0_field(wBattleScriptBuffer);
check_wram0_field(wBattleScriptBufferAddress);
check_wram0_field(wTurnEnded);
check_wram0_field(wPlayerAttack);
check_wram0_field(wPlayerDefense);
check_wram0_field(wPlayerSpeed);
check_wram0_field(wPlayerSpAtk);
check_wram0_field(wPlayerSpDef);
check_wram0_field(wEnemyAttack);
check_wram0_field(wEnemyDefense);
check_wram0_field(wEnemySpeed);
check_wram0_field(wEnemySpAtk);
check_wram0_field(wEnemySpDef);
check_wram0_field(wPlayerAtkLevel);
check_wram0_field(wPlayerDefLevel);
check_wram0_field(wPlayerSpdLevel);
check_wram0_field(wPlayerSAtkLevel);
check_wram0_field(wPlayerSDefLevel);
check_wram0_field(wPlayerAccLevel);
check_wram0_field(wPlayerEvaLevel);
check_wram0_field(wEnemyAtkLevel);
check_wram0_field(wEnemyDefLevel);
check_wram0_field(wEnemySpdLevel);
check_wram0_field(wEnemySAtkLevel);
check_wram0_field(wEnemySDefLevel);
check_wram0_field(wEnemyAccLevel);
check_wram0_field(wEnemyEvaLevel);
check_wram0_field(wEnemyTurnsTaken);
check_wram0_field(wPlayerTurnsTaken);
check_wram0_field(wPlayerSubstituteHP);
check_wram0_field(wEnemySubstituteHP);
check_wram0_field(wUnusedPlayerLockedMove);
check_wram0_field(wCurPlayerMove);
check_wram0_field(wCurEnemyMove);
check_wram0_field(wLinkBattleRNCount);
check_wram0_field(wEnemyItemState);
check_wram0_field(wCurEnemyMoveNum);
check_wram0_field(wEnemyHPAtTimeOfPlayerSwitch);
check_wram0_field(wPayDayMoney);
check_wram0_field(wSafariMonAngerCount);
check_wram0_field(wSafariMonEating);
check_wram0_field(wEnemyBackupDVs);
check_wram0_field(wAlreadyDisobeyed);
check_wram0_field(wDisabledMove);
check_wram0_field(wEnemyDisabledMove);
check_wram0_field(wWhichMonFaintedFirst);
check_wram0_field(wLastPlayerCounterMove);
check_wram0_field(wLastEnemyCounterMove);
check_wram0_field(wEnemyMinimized);
check_wram0_field(wAlreadyFailed);
check_wram0_field(wBattleParticipantsIncludingFainted);
check_wram0_field(wBattleLowHealthAlarm);
check_wram0_field(wPlayerMinimized);
check_wram0_field(wPlayerScreens);
check_wram0_field(wEnemyScreens);
check_wram0_field(wPlayerSafeguardCount);
check_wram0_field(wPlayerLightScreenCount);
check_wram0_field(wPlayerReflectCount);
check_wram0_field(wEnemySafeguardCount);
check_wram0_field(wEnemyLightScreenCount);
check_wram0_field(wEnemyReflectCount);
check_wram0_field(wBattleWeather);
check_wram0_field(wWeatherCount);
check_wram0_field(wLoweredStat);
check_wram0_field(wEffectFailed);
check_wram0_field(wFailedMessage);
check_wram0_field(wEnemyGoesFirst);
check_wram0_field(wPlayerIsSwitching);
check_wram0_field(wEnemyIsSwitching);
check_wram0_field(wPlayerUsedMoves);
check_wram0_field(wEnemyAISwitchScore);
check_wram0_field(wEnemySwitchMonParam);
check_wram0_field(wEnemySwitchMonIndex);
check_wram0_field(wTempLevel);
check_wram0_field(wLastPlayerMon);
check_wram0_field(wLastPlayerMove);
check_wram0_field(wLastEnemyMove);
check_wram0_field(wPlayerFutureSightCount);
check_wram0_field(wEnemyFutureSightCount);
check_wram0_field(wGivingExperienceToExpShareHolders);
check_wram0_field(wBackupEnemyMonBaseStats);
check_wram0_field(wBackupEnemyMonCatchRate);
check_wram0_field(wBackupEnemyMonBaseExp);
check_wram0_field(wPlayerFutureSightDamage);
check_wram0_field(wEnemyFutureSightDamage);
check_wram0_field(wPlayerRageCounter);
check_wram0_field(wEnemyRageCounter);
check_wram0_field(wBeatUpHitAtLeastOnce);
check_wram0_field(wPlayerTrappingMove);
check_wram0_field(wEnemyTrappingMove);
check_wram0_field(wPlayerWrapCount);
check_wram0_field(wEnemyWrapCount);
check_wram0_field(wPlayerCharging);
check_wram0_field(wEnemyCharging);
check_wram0_field(wBattleEnded);
check_wram0_field(wWildMonMoves);
check_wram0_field(wWildMonPP);
check_wram0_field(wAmuletCoin);
check_wram0_field(wSomeoneIsRampaging);
check_wram0_field(wPlayerJustGotFrozen);
check_wram0_field(wEnemyJustGotFrozen);
check_wram0_field(wPlayerPatchLists);
check_wram0_field(wOTPatchLists);
check_wram0_field(wMobileTransferData);
check_wram0_field(wTimeSetBuffer);
check_wram0_field(wInitHourBuffer);
check_wram0_field(wInitMinuteBuffer);
check_wram0_field(wHallOfFameTemp);
check_wram0_field(wOddEgg);
check_wram0_field(wOddEggName);
check_wram0_field(wOddEggOT);
check_wram0_field(wDebugLightColor);
check_wram0_field(wDebugDarkColor);
check_wram0_field(wDebugRedChannel);
check_wram0_field(wDebugGreenChannel);
check_wram0_field(wDebugBlueChannel);
check_wram0_field(wDebugWhiteTileColor);
check_wram0_field(wDebugLightTileColor);
check_wram0_field(wDebugDarkTileColor);
check_wram0_field(wDebugBlackTileColor);
check_wram0_field(wc608);
check_wram0_field(wc618);
check_wram0_field(wc63d);
check_wram0_field(wc642);
check_wram0_field(wc647);
check_wram0_field(wc648);
check_wram0_field(wc64a);
check_wram0_field(wc668);
check_wram0_field(wc688);
check_wram0_field(wc68a);
check_wram0_field(wc6a8);
check_wram0_field(wPokedexOrder);
check_wram0_field(wDexListingScrollOffset);
check_wram0_field(wDexListingCursor);
check_wram0_field(wDexListingEnd);
check_wram0_field(wDexListingHeight);
check_wram0_field(wCurDexMode);
check_wram0_field(wDexSearchMonType1);
check_wram0_field(wDexSearchMonType2);
check_wram0_field(wDexSearchResultCount);
check_wram0_field(wDexArrowCursorPosIndex);
check_wram0_field(wDexArrowCursorDelayCounter);
check_wram0_field(wDexArrowCursorBlinkCounter);
check_wram0_field(wDexSearchSlowpokeFrame);
check_wram0_field(wUnlockedUnownMode);
check_wram0_field(wDexCurUnownIndex);
check_wram0_field(wDexUnownCount);
check_wram0_field(wDexConvertedMonType);
check_wram0_field(wDexListingScrollOffsetBackup);
check_wram0_field(wDexListingCursorBackup);
check_wram0_field(wBackupDexListingCursor);
check_wram0_field(wBackupDexListingPage);
check_wram0_field(wDexCurLocation);
check_wram0_field(wPokedexStatus);
check_wram0_field(wPokedexDataEnd);
check_wram0_field(wPokegearPhoneDisplayPosition);
check_wram0_field(wPokegearPhoneCursorPosition);
check_wram0_field(wPokegearPhoneScrollPosition);
check_wram0_field(wPokegearPhoneSelectedPerson);
check_wram0_field(wPokegearPhoneSubmenuCursor);
check_wram0_field(wPokegearMapCursorObjectPointer);
check_wram0_field(wPokegearMapCursorLandmark);
check_wram0_field(wPokegearMapPlayerIconLandmark);
check_wram0_field(wPokegearRadioChannelBank);
check_wram0_field(wPokegearRadioChannelAddr);
check_wram0_field(wPokegearRadioMusicPlaying);
check_wram0_field(wPlayerTrademon);
check_wram0_field(wOTTrademon);
check_wram0_field(wTradeAnimAddress);
check_wram0_field(wLinkPlayer1Name);
check_wram0_field(wLinkPlayer2Name);
check_wram0_field(wLinkTradeSendmonSpecies);
check_wram0_field(wLinkTradeGetmonSpecies);
check_wram0_field(wNamingScreenDestinationPointer);
check_wram0_field(wNamingScreenCurNameLength);
check_wram0_field(wNamingScreenMaxNameLength);
check_wram0_field(wNamingScreenType);
check_wram0_field(wNamingScreenCursorObjectPointer);
check_wram0_field(wNamingScreenLastCharacter);
check_wram0_field(wNamingScreenStringEntryCoord);
check_wram0_field(wReel1);
check_wram0_field(wReel2);
check_wram0_field(wReel3);
check_wram0_field(wReel1Stopped);
check_wram0_field(wReel2Stopped);
check_wram0_field(wReel3Stopped);
check_wram0_field(wSlotBias);
check_wram0_field(wSlotBet);
check_wram0_field(wFirstTwoReelsMatching);
check_wram0_field(wFirstTwoReelsMatchingSevens);
check_wram0_field(wSlotMatched);
check_wram0_field(wCurReelStopped);
check_wram0_field(wPayout);
check_wram0_field(wCurReelXCoord);
check_wram0_field(wCurReelYCoord);
check_wram0_field(wSlotBuildingMatch);
check_wram0_field(wSlotsDataEnd);
check_wram0_field(wDeck);
check_wram0_field(wCardFlipNumCardsPlayed);
check_wram0_field(wCardFlipFaceUpCard);
check_wram0_field(wDiscardPile);
check_wram0_field(wBetaPokerSGBPals);
check_wram0_field(wBetaPokerSGBAttr);
check_wram0_field(wBetaPokerSGBCol);
check_wram0_field(wBetaPokerSGBRow);
check_wram0_field(wMemoryGameCards);
check_wram0_field(wMemoryGameLastCardPicked);
check_wram0_field(wMemoryGameCard1);
check_wram0_field(wMemoryGameCard2);
check_wram0_field(wMemoryGameCard1Location);
check_wram0_field(wMemoryGameCard2Location);
check_wram0_field(wMemoryGameNumberTriesRemaining);
check_wram0_field(wMemoryGameLastMatches);
check_wram0_field(wMemoryGameCounter);
check_wram0_field(wMemoryGameNumCardsMatched);
check_wram0_field(wPuzzlePieces);
check_wram0_field(wc6d0);
check_wram0_field(wc708);
check_wram0_field(wc709);
check_wram0_field(wc70a);
check_wram0_field(wc70b);
check_wram0_field(wc70c);
check_wram0_field(wc70d);
check_wram0_field(wc70e);
check_wram0_field(wc70f);
check_wram0_field(wc710);
check_wram0_field(wc711);
check_wram0_field(wc712);
check_wram0_field(wc719);
check_wram0_field(wc74e);
check_wram0_field(wc7b9);
check_wram0_field(wc7ba);
check_wram0_field(wc7bb);
check_wram0_field(wc7bd);
check_wram0_field(wc7d0);
check_wram0_field(wc7d1);
check_wram0_field(wc7d2);
check_wram0_field(wc7d3);
// section Unused Map Buffer
check_wram0_field(wUnusedMapBuffer);
// section Overworld Map
check_wram0_field(wOverworldMapBlocks);
check_wram0_field(wGameboyPrinter2bppSource);
check_wram0_field(wUnusedGameboyPrinterSafeCancelFlag);
check_wram0_field(wPrinterRowIndex);
check_wram0_field(wPrinterData);
check_wram0_field(wPrinterChecksum);
check_wram0_field(wPrinterHandshake);
check_wram0_field(wPrinterStatusFlags);
check_wram0_field(wHandshakeFrameDelay);
check_wram0_field(wPrinterSerialFrameDelay);
check_wram0_field(wPrinterSendByteOffset);
check_wram0_field(wPrinterSendByteCounter);
check_wram0_field(wPrinterTilemapBuffer);
check_wram0_field(wPrinterStatus);
check_wram0_field(wPrinterMargins);
check_wram0_field(wPrinterExposureTime);
check_wram0_field(wBillsPCPokemonList);
check_wram0_field(wBillsPC_ScrollPosition);
check_wram0_field(wBillsPC_CursorPosition);
check_wram0_field(wBillsPC_NumMonsInBox);
check_wram0_field(wBillsPC_NumMonsOnScreen);
check_wram0_field(wBillsPC_LoadedBox);
check_wram0_field(wBillsPC_BackupScrollPosition);
check_wram0_field(wBillsPC_BackupCursorPosition);
check_wram0_field(wBillsPC_BackupLoadedBox);
check_wram0_field(wBillsPC_MonHasMail);
check_wram0_field(wHallOfFamePokemonList);
check_wram0_field(wDebugOriginalColors);
check_wram0_field(wLinkData);
check_wram0_field(wLinkPlayerName);
check_wram0_field(wLinkPartyCount);
check_wram0_field(wLinkPartySpecies);
check_wram0_field(wLinkPartyEnd);
check_wram0_field_mapped(wLinkPlayerPartyMon, wLinkPlayerPartyMon1);
check_wram0_field_mapped(wLinkPlayerPartyMonOT, wLinkPlayerPartyMon1OT);
check_wram0_field_mapped(wLinkPlayerPartyMonNickname, wLinkPlayerPartyMon1Nickname);
check_wram0_field_mapped(wTimeCapsulePartyMon, wTimeCapsulePartyMon1);
check_wram0_field_mapped(wTimeCapsulePartyMonOT, wTimeCapsulePartyMon1OT);
check_wram0_field_mapped(wTimeCapsulePartyMonNickname, wTimeCapsulePartyMon1Nickname);
check_wram0_field(wLinkPatchList1);
check_wram0_field(wLinkPatchList2);
check_wram0_field(wCurLinkOTPartyMonTypePointer);
check_wram0_field_mapped(wLinkOTPartyMonType, wLinkOTPartyMon1Type);
check_wram0_field(wLinkPlayerMailPreamble);
check_wram0_field(wLinkPlayerMailMessages);
check_wram0_field(wLinkPlayerMailMetadata);
check_wram0_field(wLinkPlayerMailPatchSet);
check_wram0_field(wLinkPlayerMailEnd);
check_wram0_field(wLinkOTMailMessages);
check_wram0_field(wLinkOTMailMetadata);
check_wram0_field(wOTPlayerMailPatchSet);
check_wram0_field(wLinkOTMailEnd);
check_wram0_field(wLinkReceivedMail);
check_wram0_field(wLinkReceivedMailEnd);
check_wram0_field(wMysteryGiftStaging);
check_wram0_field(wMysteryGiftTrainer);
check_wram0_field(wNameCardData);
check_wram0_field(wMysteryGiftCardHolderName);
check_wram0_field(wMysteryGiftGameVersion);
check_wram0_field(wMysteryGiftPartnerID);
check_wram0_field(wMysteryGiftPartnerName);
check_wram0_field(wMysteryGiftPartnerDexCaught);
check_wram0_field(wMysteryGiftPartnerSentDeco);
check_wram0_field(wMysteryGiftPartnerWhichItem);
check_wram0_field(wMysteryGiftPartnerWhichDeco);
check_wram0_field(wMysteryGiftPartnerBackupItem);
check_wram0_field(wMysteryGiftPartnerDataEnd);
check_wram0_field(wMysteryGiftPlayerData);
check_wram0_field(wMysteryGiftPlayerID);
check_wram0_field(wMysteryGiftPlayerName);
check_wram0_field(wMysteryGiftPlayerDexCaught);
check_wram0_field(wMysteryGiftPlayerSentDeco);
check_wram0_field(wMysteryGiftPlayerWhichItem);
check_wram0_field(wMysteryGiftPlayerWhichDeco);
check_wram0_field(wMysteryGiftPlayerBackupItem);
check_wram0_field(wUnusedMysteryGiftStagedDataLength);
check_wram0_field(wMysteryGiftMessageCount);
check_wram0_field(wMysteryGiftStagedDataLength);
check_wram0_field(wCreditsBlankFrame2bpp);
check_wram0_field(wc800);
check_wram0_field(wc801);
check_wram0_field(wc802);
check_wram0_field(wc803);
check_wram0_field(wc804);
check_wram0_field(wc805);
check_wram0_field(wc806);
check_wram0_field(wc807);
check_wram0_field(wc808);
check_wram0_field(wc80a);
check_wram0_field(wc80b);
check_wram0_field(wc80c);
check_wram0_field(wc80e);
check_wram0_field(wc80f);
check_wram0_field(wc810);
check_wram0_field(wc811);
check_wram0_field(wMobileSDK_PacketChecksum);
check_wram0_field(wc814);
check_wram0_field(wc815);
check_wram0_field(wc816);
check_wram0_field(wMobileSDK_AdapterType);
check_wram0_field(wc819);
check_wram0_field(wc81a);
check_wram0_field(wc81b);
check_wram0_field(wc81c);
check_wram0_field(wc81d);
check_wram0_field(wMobileSDK_SendCommandID);
check_wram0_field(wc81f);
check_wram0_field(wc820);
check_wram0_field(wc821);
check_wram0_field(wc822);
check_wram0_field(wc823);
check_wram0_field(wc827);
check_wram0_field(wc829);
check_wram0_field(wc82a);
check_wram0_field(wc82b);
check_wram0_field(wc82c);
check_wram0_field(wc82d);
check_wram0_field(wc82e);
check_wram0_field(wc82f);
check_wram0_field(wc832);
check_wram0_field(wc833);
check_wram0_field(wc834);
check_wram0_field(wc835);
check_wram0_field(wc836);
check_wram0_field(wc83e);
check_wram0_field(wc852);
check_wram0_field(wc866);
check_wram0_field(wc86a);
check_wram0_field(wc86b);
check_wram0_field(wc86c);
check_wram0_field(wc86d);
check_wram0_field(wc86e);
check_wram0_field(wc86f);
check_wram0_field(wc870);
check_wram0_field(wc871);
check_wram0_field(wc872);
check_wram0_field(wc873);
check_wram0_field(wc874);
check_wram0_field(wc875);
check_wram0_field(wc876);
check_wram0_field(wc877);
check_wram0_field(wc878);
check_wram0_field(wc87a);
check_wram0_field(wc87b);
check_wram0_field(wc87c);
check_wram0_field(wc87d);
check_wram0_field(wc87e);
check_wram0_field(wc87f);
check_wram0_field(wc880);
check_wram0_field(wc881);
check_wram0_field(wc882);
check_wram0_field(wc883);
check_wram0_field(wc884);
check_wram0_field(wc88c);
check_wram0_field(wc8ac);
check_wram0_field(wc8c6);
check_wram0_field(wc8c7);
check_wram0_field(wc8c8);
check_wram0_field(wc8c9);
check_wram0_field(wc8ca);
check_wram0_field(wc8f6);
check_wram0_field(wc8fe);
check_wram0_field(wc8ff);
check_wram0_field(wc90e);
check_wram0_field(wc916);
check_wram0_field(wc926);
check_wram0_field(wc92e);
check_wram0_field(wc979);
check_wram0_field(wc97a);
check_wram0_field(wc97f);
check_wram0_field(wc980);
check_wram0_field(wc981);
check_wram0_field(wc982);
check_wram0_field(wc983);
check_wram0_field(wc985);
check_wram0_field(wc986);
check_wram0_field(wc987);
check_wram0_field(wMobileAPIIndex);
check_wram0_field(wc989);
check_wram0_field(wc98a);
check_wram0_field(wc98b);
check_wram0_field(wc98c);
check_wram0_field(wc98d);
check_wram0_field(wc98e);
check_wram0_field(wc98f);
check_wram0_field(wc990);
check_wram0_field(wc991);
check_wram0_field(wc992);
check_wram0_field(wc993);
check_wram0_field(wc994);
check_wram0_field(wc995);
check_wram0_field(wc9a5);
check_wram0_field(wc9aa);
check_wram0_field(wc9ab);
check_wram0_field(wc9ac);
check_wram0_field(wc9ad);
check_wram0_field(wc9ae);
check_wram0_field(wc9af);
check_wram0_field(wc9b1);
check_wram0_field(wc9b2);
check_wram0_field(wc9b5);
check_wram0_field(wc9b6);
check_wram0_field(wMobileSDK_ReceivePacketBufferAlt);
check_wram0_field(wMobileSDK_ReceivedBytes);
check_wram0_field(wMobileSDK_ReceivePacketBuffer);
check_wram0_field(wcb36);
check_wram0_field(wMobileSDK_PacketBuffer);
check_wram0_field(wcc60);
check_wram0_field(wcc61);
check_wram0_field(wcc62);
check_wram0_field(wcc64);
check_wram0_field(wcc65);
check_wram0_field(wccb4);
check_wram0_field(wccb5);
check_wram0_field(wccb8);
check_wram0_field(wccb9);
check_wram0_field(wccba);
// check_wram0_field(wDebugRoomRTCSec);
// check_wram0_field(wDebugRoomRTCMin);
// check_wram0_field(wDebugRoomRTCHour);
// check_wram0_field(wDebugRoomRTCDay);
// check_wram0_field(wDebugRoomRTCCurSec);
// check_wram0_field(wDebugRoomRTCCurMin);
// check_wram0_field(wDebugRoomRTCCurHour);
// check_wram0_field(wDebugRoomRTCCurDay);
// check_wram0_field(wDebugRoomCurPage);
// check_wram0_field(wDebugRoomCurValue);
// check_wram0_field(wDebugRoomAFunction);
// check_wram0_field(wDebugRoomStartFunction);
// check_wram0_field(wDebugRoomSelectFunction);
// check_wram0_field(wDebugRoomAutoFunction);
// check_wram0_field(wDebugRoomPageCount);
// check_wram0_field(wDebugRoomPagesPointer);
// check_wram0_field(wDebugRoomROMChecksum);
// check_wram0_field(wDebugRoomCurChecksumBank);
// check_wram0_field(wDebugRoomItemID);
// check_wram0_field(wDebugRoomItemQuantity);
// check_wram0_field(wDebugRoomMon);
// check_wram0_field(wDebugRoomMonBox);
// check_wram0_field(wDebugRoomGBID);
// section Video
check_wram0_field(wBGMapBuffer);
check_wram0_field(wBGMapPalBuffer);
check_wram0_field(wBGMapBufferPointers);
check_wram0_field(wCreditsPos);
check_wram0_field(wCreditsTimer);
check_wram0_field(wMobileMonSpeciesPointer);
check_wram0_field(wMobileMonStructPointer);
check_wram0_field(wMobileMonOTPointer);
check_wram0_field(wMobileMonNicknamePointer);
check_wram0_field(wMobileMonMailPointer);
check_wram0_field(wcd20);
check_wram0_field(wcd21);
check_wram0_field(wcd22);
check_wram0_field(wcd23);
check_wram0_field(wcd24);
check_wram0_field(wMobileCommsJumptableIndex);
check_wram0_field(wcd26);
check_wram0_field(wcd27);
check_wram0_field(wcd28);
check_wram0_field(wcd29);
check_wram0_field(wMobileMonSpecies);
check_wram0_field(wcd2a);
check_wram0_field(wTempOddEggNickname);
check_wram0_field(wcd2b);
check_wram0_field(wcd2c);
check_wram0_field(wcd2d);
check_wram0_field(wcd2e);
check_wram0_field(wcd2f);
check_wram0_field(wcd30);
check_wram0_field(wcd31);
check_wram0_field(wcd32);
check_wram0_field(wcd33);
check_wram0_field(wcd34);
check_wram0_field(wcd35);
check_wram0_field(wcd36);
check_wram0_field(wcd37);
check_wram0_field(wcd38);
check_wram0_field(wcd39);
check_wram0_field(wcd3a);
check_wram0_field(wcd3b);
check_wram0_field(wBattleTowerRoomMenu2JumptableIndex);
check_wram0_field(wcd3d);
check_wram0_field(wcd3e);
check_wram0_field(wcd3f);
check_wram0_field(wcd40);
check_wram0_field(wcd41);
check_wram0_field(wcd42);
check_wram0_field(wcd43);
check_wram0_field(wMobileInactivityTimerMinutes);
check_wram0_field(wMobileInactivityTimerSeconds);
check_wram0_field(wMobileInactivityTimerFrames);
check_wram0_field(wcd47);
check_wram0_field(wcd49);
check_wram0_field(wcd4a);
check_wram0_field(wcd4b);
check_wram0_field(wEZChatCursorXCoord);
check_wram0_field(wcd4c);
check_wram0_field(wEZChatCursorYCoord);
check_wram0_field(wcd4d);
check_wram0_field(wcd4e);
check_wram0_field(wcd4f);
check_wram0_field(wcd50);
check_wram0_field(wcd51);
check_wram0_field(wcd52);
check_wram0_field(wcd53);
check_wram0_field(wcd54);
check_wram0_field(wcd55);
check_wram0_field(wcd56);
check_wram0_field(wcd57);
check_wram0_field(wcd58);
check_wram0_field(wcd59);
check_wram0_field(wcd5a);
check_wram0_field(wcd5b);
check_wram0_field(wcd5c);
check_wram0_field(wcd5d);
check_wram0_field(wcd5e);
check_wram0_field(wcd5f);
check_wram0_field(wcd60);
check_wram0_field(wcd62);
check_wram0_field(wcd63);
check_wram0_field(wcd64);
check_wram0_field(wcd65);
check_wram0_field(wcd66);
check_wram0_field(wcd67);
check_wram0_field(wcd68);
check_wram0_field(wcd69);
check_wram0_field(wcd6a);
check_wram0_field(wcd6b);
check_wram0_field(wcd6c);
check_wram0_field(wcd6d);
check_wram0_field(wcd6e);
check_wram0_field(wcd6f);
check_wram0_field(wcd70);
check_wram0_field(wcd71);
check_wram0_field(wcd72);
check_wram0_field(wcd73);
check_wram0_field(wcd74);
check_wram0_field(wOTMonSelection);
check_wram0_field(wcd77);
check_wram0_field(wMobileCrashCheckPointer);
check_wram0_field(wcd7a);
check_wram0_field(wcd7c);
check_wram0_field(wcd7f);
check_wram0_field(wcd80);
check_wram0_field(wcd81);
check_wram0_field(wcd82);
check_wram0_field(wcd83);
check_wram0_field(wcd84);
check_wram0_field(wcd85);
check_wram0_field(wcd89);
check_wram0_field(wcd8a);
check_wram0_field(wcd8b);
check_wram0_field(wcd8c);
check_wram0_field(wcd8d);
check_wram0_field(wDefaultSGBLayout);
check_wram0_field(wPlayerHPPal);
check_wram0_field(wEnemyHPPal);
check_wram0_field(wHPPals);
check_wram0_field(wCurHPPal);
check_wram0_field(wSGBPals);
check_wram0_field(wAttrmap);
check_wram0_field(wcf42);
check_wram0_field(wcf44);
check_wram0_field(wcf45);
check_wram0_field(wTileAnimBuffer);
check_wram0_field(wOtherPlayerLinkMode);
check_wram0_field(wOtherPlayerLinkAction);
check_wram0_field(wPlayerLinkAction);
check_wram0_field(wUnusedLinkAction);
check_wram0_field(wLinkReceivedSyncBuffer);
check_wram0_field(wLinkPlayerSyncBuffer);
check_wram0_field(wLinkTimeoutFrames);
check_wram0_field(wLinkByteTimeout);
check_wram0_field(wMonType);
check_wram0_field(wCurSpecies);
check_wram0_field(wNamedObjectType);
check_wram0_field(wJumptableIndex);
check_wram0_field(wBattleTowerBattleEnded);
check_wram0_field(wIntroSceneFrameCounter);
check_wram0_field(wIntroSceneTimer);
check_wram0_field(wTitleScreenSelectedOption);
check_wram0_field(wTitleScreenTimer);
check_wram0_field(wCreditsBorderFrame);
check_wram0_field(wCreditsBorderMon);
check_wram0_field(wCreditsLYOverride);
check_wram0_field(wPrevDexEntryJumptableIndex);
check_wram0_field(wPrevDexEntryBackup);
check_wram0_field(wPokedexStatus);
check_wram0_field(wUnusedPokedexByte);
check_wram0_field(wPokegearCard);
check_wram0_field(wPokegearMapRegion);
check_wram0_field(wUnusedPokegearByte);
check_wram0_field(wPackJumptableIndex);
check_wram0_field(wCurPocket);
check_wram0_field(wPackUsedItem);
check_wram0_field(wTrainerCardBadgeFrameCounter);
check_wram0_field(wTrainerCardBadgeTileID);
check_wram0_field(wTrainerCardBadgeAttributes);
check_wram0_field(wSlotsDelay);
check_wram0_field(wUnusedSlotReelIconDelay);
check_wram0_field(wCardFlipCursorY);
check_wram0_field(wCardFlipCursorX);
check_wram0_field(wCardFlipWhichCard);
check_wram0_field(wMemoryGameCardChoice);
check_wram0_field(wMagnetTrainOffset);
check_wram0_field(wMagnetTrainPosition);
check_wram0_field(wMagnetTrainWaitCounter);
check_wram0_field(wHoldingUnownPuzzlePiece);
check_wram0_field(wUnownPuzzleCursorPosition);
check_wram0_field(wUnownPuzzleHeldPiece);
check_wram0_field(wBattleTransitionCounter);
check_wram0_field(wBattleTransitionSpinQuadrant);
check_wram0_field(wUnusedBillsPCData);
check_wram0_field(wDebugColorRGBJumptableIndex);
check_wram0_field(wDebugColorCurColor);
check_wram0_field(wDebugColorCurMon);
check_wram0_field(wDebugTilesetCurPalette);
check_wram0_field(wDebugTilesetRGBJumptableIndex);
check_wram0_field(wDebugTilesetCurColor);
check_wram0_field(wStatsScreenFlags);
check_wram0_field(wNrOfBeatenBattleTowerTrainers);
check_wram0_field(wBattleTowerRoomMenuJumptableIndex);
check_wram0_field(wFrameCounter);
check_wram0_field(wMomBankDigitCursorPosition);
check_wram0_field(wNamingScreenLetterCase);
check_wram0_field(wHallOfFameMonCounter);
check_wram0_field(wTradeDialog);
check_wram0_field(wFrameCounter2);
check_wram0_field(wPrinterQueueLength);
check_wram0_field(wUnusedSGB1eColorOffset);
check_wram0_field(wUnusedTradeAnimPlayEvolutionMusic);
check_wram0_field(wcf64);
check_wram0_field(wcf65);
check_wram0_field(wcf66);
check_wram0_field(wRequested2bppSize);
check_wram0_field(wRequested2bppSource);
check_wram0_field(wRequested2bppDest);
check_wram0_field(wRequested1bppSize);
check_wram0_field(wRequested1bppSource);
check_wram0_field(wRequested1bppDest);
check_wram0_field(wWindowStackPointer);
check_wram0_field(wMenuJoypad);
check_wram0_field(wMenuSelection);
check_wram0_field(wMenuSelectionQuantity);
check_wram0_field(wWhichIndexSet);
check_wram0_field(wScrollingMenuCursorPosition);
check_wram0_field(wWindowStackSize);
check_wram0_field(wMenuFlags);
check_wram0_field(wMenuBorderTopCoord);
check_wram0_field(wMenuBorderLeftCoord);
check_wram0_field(wMenuBorderBottomCoord);
check_wram0_field(wMenuBorderRightCoord);
check_wram0_field(wMenuDataPointer);
check_wram0_field(wMenuCursorPosition);
check_wram0_field(wMenuDataBank);
check_wram0_field(wMenuDataFlags);
check_wram0_field(wMenuDataItems);
check_wram0_field(wMenuDataIndicesPointer);
check_wram0_field(wMenuDataDisplayFunctionPointer);
check_wram0_field(wMenuDataPointerTableAddr);
check_wram0_field(wMenuData_2DMenuDimensions);
check_wram0_field(wMenuData_2DMenuSpacing);
check_wram0_field(wMenuData_2DMenuItemStringsBank);
check_wram0_field(wMenuData_2DMenuItemStringsAddr);
check_wram0_field(wMenuData_2DMenuFunctionBank);
check_wram0_field(wMenuData_2DMenuFunctionAddr);
check_wram0_field(wMenuData_ScrollingMenuHeight);
check_wram0_field(wMenuData_ScrollingMenuWidth);
check_wram0_field(wMenuData_ScrollingMenuItemFormat);
check_wram0_field(wMenuData_ItemsPointerBank);
check_wram0_field(wMenuData_ItemsPointerAddr);
check_wram0_field(wMenuData_ScrollingMenuFunction1);
check_wram0_field(wMenuData_ScrollingMenuFunction2);
check_wram0_field(wMenuData_ScrollingMenuFunction3);
check_wram0_field(w2DMenuCursorInitY);
check_wram0_field(w2DMenuCursorInitX);
check_wram0_field(w2DMenuNumRows);
check_wram0_field(w2DMenuNumCols);
check_wram0_field(w2DMenuFlags1);
check_wram0_field(w2DMenuFlags2);
check_wram0_field(w2DMenuCursorOffsets);
check_wram0_field(wMenuJoypadFilter);
check_wram0_field(wMenuCursorY);
check_wram0_field(wMenuCursorX);
check_wram0_field(wCursorOffCharacter);
check_wram0_field(wCursorCurrentTile);
check_wram0_field(wOverworldDelay);
check_wram0_field(wTextDelayFrames);
check_wram0_field(wVBlankOccurred);
check_wram0_field(wPredefID);
check_wram0_field(wPredefHL);
check_wram0_field(wPredefAddress);
check_wram0_field(wFarCallBC);
check_wram0_field(wUnusedLinkCommunicationByte);
check_wram0_field(wGameTimerPaused);
check_wram0_field(wJoypadDisable);
check_wram0_field(wInBattleTowerBattle);
check_wram0_field(wFXAnimID);
check_wram0_field(wPlaceBallsX);
check_wram0_field(wPlaceBallsY);
check_wram0_field(wTileAnimationTimer);
check_wram0_field(wBGP);
check_wram0_field(wOBP0);
check_wram0_field(wOBP1);
check_wram0_field(wNumHits);
check_wram0_field(wOptions);
check_wram0_field(wSaveFileExists);
check_wram0_field(wTextboxFrame);
check_wram0_field(wTextboxFlags);
check_wram0_field(wGBPrinterBrightness);
check_wram0_field(wOptions2);
// check_wram0_field(wSecondsSince);
// check_wram0_field(wMinutesSince);
// check_wram0_field(wHoursSince);
// check_wram0_field(wDaysSince);
// bank 1
// section WRAM 1
check_wramx_field(wBetaTitleSequenceOpeningType, 1);
check_wramx_field(wDefaultSpawnpoint, 1);
// section Miscellaneous WRAM 1
check_wramx_field(wBufferMonNickname, 1);
check_wramx_field(wBufferMonOT, 1);
check_wramx_field(wBufferMon, 1);
check_wramx_field(wMonOrItemNameBuffer, 1);
check_wramx_field(wSeerAction, 1);
check_wramx_field(wSeerNickname, 1);
check_wramx_field(wSeerCaughtLocation, 1);
check_wramx_field(wSeerTimeOfDay, 1);
check_wramx_field(wSeerOT, 1);
check_wramx_field(wSeerOTGrammar, 1);
check_wramx_field(wSeerCaughtLevelString, 1);
check_wramx_field(wSeerCaughtLevel, 1);
check_wramx_field(wSeerCaughtData, 1);
check_wramx_field(wSeerCaughtGender, 1);
check_wramx_field(wTempMail, 1);
check_wramx_field_mapped(wBugContestWinners, 1, wBugContestResults);
check_wramx_field_mapped(wBugContestTemp, 1, wBugContestWinnersEnd);
check_wramx_field(wBugContestWinnerName, 1);
check_wramx_field(wMartItem1BCD, 1);
check_wramx_field(wMartItem2BCD, 1);
check_wramx_field(wMartItem3BCD, 1);
check_wramx_field(wMartItem4BCD, 1);
check_wramx_field(wMartItem5BCD, 1);
check_wramx_field(wMartItem6BCD, 1);
check_wramx_field(wMartItem7BCD, 1);
check_wramx_field(wMartItem8BCD, 1);
check_wramx_field(wMartItem9BCD, 1);
check_wramx_field(wMartItem10BCD, 1);
check_wramx_field(wTownMapPlayerIconLandmark, 1);
check_wramx_field(wTownMapCursorLandmark, 1);
check_wramx_field(wTownMapCursorObjectPointer, 1);
check_wramx_field(wTownMapCursorCoordinates, 1);
check_wramx_field(wStartFlypoint, 1);
check_wramx_field(wEndFlypoint, 1);
check_wramx_field(wPhoneScriptBank, 1);
check_wramx_field(wPhoneCaller, 1);
check_wramx_field(wCurRadioLine, 1);
check_wramx_field(wNextRadioLine, 1);
check_wramx_field(wRadioTextDelay, 1);
check_wramx_field(wNumRadioLinesPrinted, 1);
check_wramx_field(wOaksPKMNTalkSegmentCounter, 1);
check_wramx_field(wRadioText, 1);
check_wramx_field(wLuckyNumberDigitsBuffer, 1);
check_wramx_field(wMovementBufferCount, 1);
check_wramx_field(wMovementBufferObject, 1);
check_wramx_field(wUnusedMovementBufferBank, 1);
check_wramx_field(wUnusedMovementBufferPointer, 1);
check_wramx_field(wMovementBuffer, 1);
check_wramx_field(wWhichBoxMonToPrint, 1);
check_wramx_field(wFinishedPrintingBox, 1);
check_wramx_field(wAddrOfBoxToPrint, 1);
check_wramx_field(wBankOfBoxToPrint, 1);
check_wramx_field(wWhichBoxToPrint, 1);
check_wramx_field(wPrintedUnownTileSource, 1);
check_wramx_field(wPrintedUnownTileDest, 1);
check_wramx_field(wPlaceBallsDirection, 1);
check_wramx_field(wTrainerHUDTiles, 1);
check_wramx_field(wMobileParticipant1Nickname, 1);
check_wramx_field(wMobileParticipant2Nickname, 1);
check_wramx_field(wMobileParticipant3Nickname, 1);
check_wramx_field(wExperienceGained, 1);
check_wramx_field(wEarthquakeMovementDataBuffer, 1);
check_wramx_field(wSwitchItemBuffer, 1);
check_wramx_field(wSwitchMonBuffer, 1);
check_wramx_field(wMonMailMessageBuffer, 1);
check_wramx_field(wBoxNameBuffer, 1);
check_wramx_field(wBillsPCTempListIndex, 1);
check_wramx_field(wBillsPCTempBoxCount, 1);
check_wramx_field(wTempPokedexSeenCount, 1);
check_wramx_field(wTempPokedexCaughtCount, 1);
check_wramx_field(wDecoNameBuffer, 1);
check_wramx_field(wNumOwnedDecoCategories, 1);
check_wramx_field(wOwnedDecoCategories, 1);
check_wramx_field(wCurTradePartyMon, 1);
check_wramx_field(wCurOTTradePartyMon, 1);
check_wramx_field(wBufferTrademonNickname, 1);
check_wramx_field(wLinkBattleRecordName, 1);
check_wramx_field(wLinkBattleRecordWins, 1);
check_wramx_field(wLinkBattleRecordLosses, 1);
check_wramx_field(wLinkBattleRecordDraws, 1);
check_wramx_field(wTempDayOfWeek, 1);
check_wramx_field(wPrevPartyLevel, 1);
check_wramx_field(wCurBeatUpPartyMon, 1);
check_wramx_field(wUnownPuzzleCornerTile, 1);
check_wramx_field(wKeepSevenBiasChance, 1);
check_wramx_field(wPokeFluteCuredSleep, 1);
check_wramx_field(wTempRestorePPItem, 1);
check_wramx_field(wApricorns, 1);
check_wramx_field(wSuicuneFrame, 1);
check_wramx_field(wDebugColorIsTrainer, 1);
check_wramx_field(wDebugColorIsShiny, 1);
check_wramx_field(wDebugColorCurTMHM, 1);
check_wramx_field(wd002, 1);
check_wramx_field(wd003, 1);
check_wramx_field(wd004, 1);
check_wramx_field(wd008, 1);
check_wramx_field(wd010, 1);
check_wramx_field(wd011, 1);
check_wramx_field(wd012, 1);
check_wramx_field(wd013, 1);
check_wramx_field(wd014, 1);
check_wramx_field(wd017, 1);
check_wramx_field(wd018, 1);
check_wramx_field(wd019, 1);
check_wramx_field(wd02d, 1);
check_wramx_field(wd02e, 1);
check_wramx_field(wd02f, 1);
check_wramx_field(wd030, 1);
check_wramx_field(wd031, 1);
check_wramx_field(wd032, 1);
check_wramx_field(wd033, 1);
check_wramx_field(wd034, 1);
check_wramx_field(wd036, 1);
check_wramx_field(wSeenTrainerBank, 1);
check_wramx_field(wSeenTrainerDistance, 1);
check_wramx_field(wSeenTrainerDirection, 1);
check_wramx_field(wTempTrainerEventFlag, 1);
check_wramx_field(wTempTrainerClass, 1);
check_wramx_field(wTempTrainerID, 1);
check_wramx_field(wSeenTextPointer, 1);
check_wramx_field(wWinTextPointer, 1);
check_wramx_field(wLossTextPointer, 1);
check_wramx_field(wScriptAfterPointer, 1);
check_wramx_field(wRunningTrainerBattleScript, 1);
check_wramx_field(wMenuItemsList, 1);
check_wramx_field(wCurFruitTree, 1);
check_wramx_field(wCurFruit, 1);
check_wramx_field(wItemBallItemID, 1);
check_wramx_field(wItemBallQuantity, 1);
check_wramx_field(wHiddenItemEvent, 1);
check_wramx_field(wHiddenItemID, 1);
check_wramx_field(wElevatorPointerBank, 1);
check_wramx_field(wElevatorPointer, 1);
check_wramx_field(wElevatorOriginFloor, 1);
check_wramx_field(wCurCoordEventSceneID, 1);
check_wramx_field(wCurCoordEventMapY, 1);
check_wramx_field(wCurCoordEventMapX, 1);
check_wramx_field(wCurCoordEventScriptAddr, 1);
check_wramx_field(wCurBGEventYCoord, 1);
check_wramx_field(wCurBGEventXCoord, 1);
check_wramx_field(wCurBGEventType, 1);
check_wramx_field(wCurBGEventScriptAddr, 1);
check_wramx_field(wMartType, 1);
check_wramx_field(wMartPointerBank, 1);
check_wramx_field(wMartPointer, 1);
check_wramx_field(wMartJumptableIndex, 1);
check_wramx_field(wBargainShopFlags, 1);
check_wramx_field(wFacingTileID, 1);
check_wramx_field(wWalkingIntoNPC, 1);
check_wramx_field(wWalkingIntoLand, 1);
check_wramx_field(wWalkingIntoEdgeWarp, 1);
check_wramx_field(wMovementAnimation, 1);
check_wramx_field(wWalkingDirection, 1);
check_wramx_field(wFacingDirection, 1);
check_wramx_field(wWalkingX, 1);
check_wramx_field(wWalkingY, 1);
check_wramx_field(wWalkingTile, 1);
check_wramx_field(wPlayerTurningDirection, 1);
check_wramx_field(wJumpStdScriptBuffer, 1);
check_wramx_field(wCheckedTime, 1);
check_wramx_field(wPhoneListIndex, 1);
check_wramx_field(wNumAvailableCallers, 1);
check_wramx_field(wAvailableCallers, 1);
check_wramx_field(wCallerContact, 1);
check_wramx_field(wMenuCursorPositionBackup, 1);
check_wramx_field(wMenuScrollPositionBackup, 1);
check_wramx_field(wPoisonStepFlagSum, 1);
check_wramx_field(wPoisonStepPartyFlags, 1);
// section More WRAM 1
check_wramx_field(wTMHMMoveNameBackup, 1);
check_wramx_field(wStringBuffer1, 1);
check_wramx_field(wStringBuffer2, 1);
check_wramx_field(wStringBuffer3, 1);
check_wramx_field(wStringBuffer4, 1);
check_wramx_field(wStringBuffer5, 1);
check_wramx_field(wBattleMenuCursorPosition, 1);
check_wramx_field(wCurBattleMon, 1);
check_wramx_field(wCurMoveNum, 1);
check_wramx_field(wLastPocket, 1);
check_wramx_field(wPCItemsCursor, 1);
check_wramx_field(wPartyMenuCursor, 1);
check_wramx_field(wItemsPocketCursor, 1);
check_wramx_field(wKeyItemsPocketCursor, 1);
check_wramx_field(wBallsPocketCursor, 1);
check_wramx_field(wTMHMPocketCursor, 1);
check_wramx_field(wPCItemsScrollPosition, 1);
check_wramx_field(wItemsPocketScrollPosition, 1);
check_wramx_field(wKeyItemsPocketScrollPosition, 1);
check_wramx_field(wBallsPocketScrollPosition, 1);
check_wramx_field(wTMHMPocketScrollPosition, 1);
check_wramx_field(wSwitchMon, 1);
check_wramx_field(wSwitchItem, 1);
check_wramx_field(wSwappingMove, 1);
check_wramx_field(wd0e3, 1);
check_wramx_field(wMenuScrollPosition, 1);
check_wramx_field_mapped(legacyQueuedScriptReserved, 1, wQueuedScriptBank);
check_wramx_field(wNumMoves, 1);
check_wramx_field(wFieldMoveSucceeded, 1);
check_wramx_field(wItemEffectSucceeded, 1);
check_wramx_field(wBattlePlayerAction, 1);
check_wramx_field(wSolvedUnownPuzzle, 1);
check_wramx_field(wVramState, 1);
check_wramx_field(wBattleResult, 1);
check_wramx_field(wUsingItemWithSelect, 1);
check_wramx_field(wCurMartCount, 1);
check_wramx_field(wCurMartItems, 1);
check_wramx_field(wCurElevatorCount, 1);
check_wramx_field(wCurElevatorFloors, 1);
check_wramx_field(wCurMessageScrollPosition, 1);
check_wramx_field(wCurMessageIndex, 1);
check_wramx_field(wMailboxCount, 1);
check_wramx_field(wMailboxItems, 1);
check_wramx_field(wListPointer, 1);
check_wramx_field(wUnusedNamesPointer, 1);
check_wramx_field(wItemAttributesPointer, 1);
check_wramx_field(wCurItem, 1);
check_wramx_field(wMartItemID, 1);
check_wramx_field(wCurPartySpecies, 1);
check_wramx_field(wCurPartyMon, 1);
check_wramx_field(wWhichHPBar, 1);
check_wramx_field(wPokemonWithdrawDepositParameter, 1);
check_wramx_field(wItemQuantityChange, 1);
check_wramx_field(wItemQuantity, 1);
check_wramx_field(wTempMon, 1);
check_wramx_field(wSpriteFlags, 1);
check_wramx_field(wHandlePlayerStep, 1);
check_wramx_field(wPartyMenuActionText, 1);
check_wramx_field(wItemAttributeValue, 1);
check_wramx_field(wCurPartyLevel, 1);
check_wramx_field(wScrollingMenuListSize, 1);
check_wramx_field(wNextWarp, 1);
check_wramx_field(wNextMapGroup, 1);
check_wramx_field(wNextMapNumber, 1);
check_wramx_field(wPrevWarp, 1);
check_wramx_field(wPrevMapGroup, 1);
check_wramx_field(wPrevMapNumber, 1);
check_wramx_field(wPlayerBGMapOffsetX, 1);
check_wramx_field(wPlayerBGMapOffsetY, 1);
check_wramx_field(wPlayerStepVectorX, 1);
check_wramx_field(wPlayerStepVectorY, 1);
check_wramx_field(wPlayerStepFlags, 1);
check_wramx_field(wPlayerStepDirection, 1);
check_wramx_field(wBGMapAnchor, 1);
check_wramx_field(wUsedSprites, 1);
check_wramx_field(wd173, 1);
check_wramx_field(wOverworldMapAnchor, 1);
check_wramx_field(wMetatileStandingY, 1);
check_wramx_field(wMetatileStandingX, 1);
check_wramx_field(wMapAttributesBank, 1);
check_wramx_field(wMapTileset, 1);
check_wramx_field(wEnvironment, 1);
check_wramx_field(wMapAttributesPointer, 1);
check_wramx_field(wMapBorderBlock, 1);
check_wramx_field(wMapHeight, 1);
check_wramx_field(wMapWidth, 1);
check_wramx_field(wMapBlocksBank, 1);
check_wramx_field(wMapBlocksPointer, 1);
check_wramx_field(wMapScriptsBank, 1);
check_wramx_field(wMapScriptsPointer, 1);
check_wramx_field(wMapEventsPointer, 1);
check_wramx_field(wMapConnections, 1);
check_wramx_field(wNorthMapConnection, 1);
check_wramx_field(wSouthMapConnection, 1);
check_wramx_field(wWestMapConnection, 1);
check_wramx_field(wEastMapConnection, 1);
check_wramx_field(wTilesetBank, 1);
check_wramx_field(wTilesetAddress, 1);
check_wramx_field(wTilesetBlocksBank, 1);
check_wramx_field(wTilesetBlocksAddress, 1);
check_wramx_field(wTilesetCollisionBank, 1);
check_wramx_field(wTilesetCollisionAddress, 1);
check_wramx_field(wTilesetAnim, 1);
check_wramx_field(wTilesetPalettes, 1);
check_wramx_field(wEvolvableFlags, 1);
check_wramx_field(wForceEvolution, 1);
check_wramx_field(wHPBuffer1, 1);
check_wramx_field(wHPBuffer2, 1);
check_wramx_field(wHPBuffer3, 1);
check_wramx_field(wCurHPAnimMaxHP, 1);
check_wramx_field(wCurHPAnimOldHP, 1);
check_wramx_field(wCurHPAnimNewHP, 1);
check_wramx_field(wCurHPAnimPal, 1);
check_wramx_field(wCurHPBarPixels, 1);
check_wramx_field(wNewHPBarPixels, 1);
check_wramx_field(wCurHPAnimDeltaHP, 1);
check_wramx_field(wCurHPAnimLowHP, 1);
check_wramx_field(wCurHPAnimHighHP, 1);
check_wramx_field(wEnemyAIMoveScores, 1);
check_wramx_field(wEnemyEffectivenessVsPlayerMons, 1);
check_wramx_field(wPlayerEffectivenessVsEnemyMons, 1);
check_wramx_field(wBattleHUDTiles, 1);
check_wramx_field(wFinalCatchRate, 1);
check_wramx_field(wThrownBallWobbleCount, 1);
check_wramx_field(wEvolutionOldSpecies, 1);
check_wramx_field(wEvolutionNewSpecies, 1);
check_wramx_field(wEvolutionPicOffset, 1);
check_wramx_field(wEvolutionCanceled, 1);
check_wramx_field(wExpToNextLevel, 1);
check_wramx_field(wPPUpPPBuffer, 1);
check_wramx_field(wMonIDDigitsBuffer, 1);
check_wramx_field(wMonSubmenuCount, 1);
check_wramx_field(wMonSubmenuItems, 1);
check_wramx_field(wFieldMoveJumptableIndex, 1);
check_wramx_field(wEscapeRopeOrDigType, 1);
check_wramx_field(wSurfingPlayerState, 1);
check_wramx_field(wFishingRodUsed, 1);
check_wramx_field(wCutWhirlpoolOverworldBlockAddr, 1);
check_wramx_field(wCutWhirlpoolReplacementBlock, 1);
check_wramx_field(wCutWhirlpoolAnimationType, 1);
check_wramx_field(wStrengthSpecies, 1);
check_wramx_field(wFishingResult, 1);
check_wramx_field(wCurMapScriptBank, 1);
check_wramx_field(wRemainingBGEventCount, 1);
check_wramx_field(wBottomRightYCoord, 1);
check_wramx_field(wBottomRightXCoord, 1);
check_wramx_field(wHealMachineAnimType, 1);
check_wramx_field(wHealMachineTempOBP1, 1);
check_wramx_field(wHealMachineAnimState, 1);
check_wramx_field(wCurDecoration, 1);
check_wramx_field(wSelectedDecorationSide, 1);
check_wramx_field(wSelectedDecoration, 1);
check_wramx_field(wOtherDecoration, 1);
check_wramx_field(wChangedDecorations, 1);
check_wramx_field(wCurDecorationCategory, 1);
check_wramx_field(wPCItemQuantityChange, 1);
check_wramx_field(wPCItemQuantity, 1);
check_wramx_field(wCurMailAuthorID, 1);
check_wramx_field(wCurMailIndex, 1);
check_wramx_field(wKurtApricornCount, 1);
check_wramx_field(wKurtApricornItems, 1);
check_wramx_field(wTreeMonCoordScore, 1);
check_wramx_field(wTreeMonOTIDScore, 1);
check_wramx_field(wRestartClockCurDivision, 1);
check_wramx_field(wRestartClockPrevDivision, 1);
check_wramx_field(wRestartClockUpArrowYCoord, 1);
check_wramx_field(wRestartClockDay, 1);
check_wramx_field(wRestartClockHour, 1);
check_wramx_field(wRestartClockMin, 1);
check_wramx_field(wLinkBattleRNPreamble, 1);
check_wramx_field(wLinkBattleRNs, 1);
check_wramx_field(wd1ea, 1);
check_wramx_field(wd1eb, 1);
check_wramx_field(wd1ec, 1);
check_wramx_field(wd1ed, 1);
check_wramx_field(wd1ee, 1);
check_wramx_field(wd1ef, 1);
check_wramx_field(wd1f0, 1);
check_wramx_field(wd1f1, 1);
check_wramx_field(wd1f2, 1);
check_wramx_field(wd1f3, 1);
check_wramx_field(wSkipMovesBeforeLevelUp, 1);
check_wramx_field(wRegisteredPhoneNumbers, 1);
check_wramx_field(wListMovesLineSpacing, 1);
check_wramx_field(wSwitchMonTo, 1);
check_wramx_field(wSwitchMonFrom, 1);
check_wramx_field(wCurEnemyItem, 1);
check_wramx_field(wBuySellItemPrice, 1);
check_wramx_field(wTempMysteryGiftTimer, 1);
check_wramx_field(wMagikarpLength, 1);
check_wramx_field(wTempEnemyMonSpecies, 1);
check_wramx_field(wTempBattleMonSpecies, 1);
check_wramx_field(wEnemyMon, 1);
check_wramx_field(wEnemyMonBaseStats, 1);
check_wramx_field(wEnemyMonCatchRate, 1);
check_wramx_field(wEnemyMonBaseExp, 1);
check_wramx_field(wBattleMode, 1);
check_wramx_field(wTempWildMonSpecies, 1);
check_wramx_field(wOtherTrainerClass, 1);
check_wramx_field(wBattleType, 1);
check_wramx_field(wOtherTrainerID, 1);
check_wramx_field(wForcedSwitch, 1);
check_wramx_field(wTrainerClass, 1);
check_wramx_field(wUnownLetter, 1);
check_wramx_field(wMoveSelectionMenuType, 1);
check_wramx_field(wBaseDexNo, 1);
check_wramx_field(wBaseHP, 1);
check_wramx_field(wBaseAttack, 1);
check_wramx_field(wBaseDefense, 1);
check_wramx_field(wBaseSpeed, 1);
check_wramx_field(wBaseSpecialAttack, 1);
check_wramx_field(wBaseSpecialDefense, 1);
check_wramx_field(wBaseType1, 1);
check_wramx_field(wBaseType2, 1);
check_wramx_field(wBaseCatchRate, 1);
check_wramx_field(wBaseExp, 1);
check_wramx_field(wBaseItem1, 1);
check_wramx_field(wBaseItem2, 1);
check_wramx_field(wBaseGender, 1);
check_wramx_field(wBaseUnknown1, 1);
check_wramx_field(wBaseEggSteps, 1);
check_wramx_field(wBaseUnknown2, 1);
check_wramx_field(wBasePicSize, 1);
check_wramx_field(wBaseUnusedFrontpic, 1);
check_wramx_field(wBaseUnusedBackpic, 1);
check_wramx_field(wBaseGrowthRate, 1);
check_wramx_field(wBaseEggGroups, 1);
check_wramx_field(wBaseTMHM, 1);
check_wramx_field(wCurDamage, 1);
check_wramx_field(wMornEncounterRate, 1);
check_wramx_field(wDayEncounterRate, 1);
check_wramx_field(wNiteEncounterRate, 1);
check_wramx_field(wWaterEncounterRate, 1);
check_wramx_field(wListMoves_MoveIndicesBuffer, 1);
check_wramx_field(wPutativeTMHMMove, 1);
check_wramx_field(wInitListType, 1);
check_wramx_field(wBattleHasJustStarted, 1);
check_wramx_field(wNamedObjectIndex, 1);
check_wramx_field(wTextDecimalByte, 1);
check_wramx_field(wTempByteValue, 1);
check_wramx_field(wNumSetBits, 1);
check_wramx_field(wTypeMatchup, 1);
check_wramx_field(wCurType, 1);
check_wramx_field(wTempSpecies, 1);
check_wramx_field(wTempIconSpecies, 1);
check_wramx_field(wTempTMHM, 1);
check_wramx_field(wTempPP, 1);
check_wramx_field(wNextBoxOrPartyIndex, 1);
check_wramx_field(wChosenCableClubRoom, 1);
check_wramx_field(wBreedingCompatibility, 1);
check_wramx_field(wMoveGrammar, 1);
check_wramx_field(wApplyStatLevelMultipliersToEnemy, 1);
check_wramx_field(wUsePPUp, 1);
check_wramx_field(wd265, 1);
check_wramx_field(wFailedToFlee, 1);
check_wramx_field(wNumFleeAttempts, 1);
check_wramx_field(wMonTriedToEvolve, 1);
check_wramx_field(wTimeOfDay, 1);
// section Enemy Party
check_wramx_field(wPokedexShowPointerAddr, 1);
check_wramx_field(wPokedexShowPointerBank, 1);
check_wramx_field(wd271, 1);
check_wramx_field(wUnusedEggHatchFlag, 1);
check_wramx_field(wOTPlayerName, 1);
check_wramx_field(wOTPlayerID, 1);
check_wramx_field(wOTPartyCount, 1);
check_wramx_field(wOTPartySpecies, 1);
check_wramx_field(wOTPartyEnd, 1);
check_wramx_field_mapped(wOTPartyMon, 1, wOTPartyMon1);
check_wramx_field_mapped(wOTPartyMonOT, 1, wOTPartyMon1OT);
check_wramx_field_mapped(wOTPartyMonNickname, 1, wOTPartyMon1Nickname);
check_wramx_field(wDudeNumItems, 1);
check_wramx_field(wDudeItems, 1);
check_wramx_field(wDudeNumKeyItems, 1);
check_wramx_field(wDudeKeyItems, 1);
check_wramx_field(wDudeNumBalls, 1);
check_wramx_field(wDudeBalls, 1);
check_wramx_field(wd430, 1);
check_wramx_field(wBattleAction, 1);
check_wramx_field(wLinkBattleSentAction, 1);
check_wramx_field(wMapStatus, 1);
check_wramx_field(wMapEventStatus, 1);
check_wramx_field(wScriptFlags, 1);
check_wramx_field(wScriptFlags2, 1);
check_wramx_field(wScriptMode, 1);
check_wramx_field(wScriptRunning, 1);
check_wramx_field(wScriptBank, 1);
check_wramx_field(wScriptPos, 1);
check_wramx_field(wScriptStackSize, 1);
check_wramx_field(wScriptStack, 1);
check_wramx_field(wScriptDelay, 1);
check_wramx_field(wDeferredScriptBank, 1);
check_wramx_field(wScriptTextBank, 1);
check_wramx_field(wDeferredScriptAddr, 1);
check_wramx_field(wScriptTextAddr, 1);
check_wramx_field(wWildEncounterCooldown, 1);
check_wramx_field(wXYComparePointer, 1);
check_wramx_field(wBattleScriptFlags, 1);
check_wramx_field(wPlayerSpriteSetupFlags, 1);
check_wramx_field(wMapReentryScriptQueueFlag, 1);
check_wramx_field(wMapReentryScriptBank, 1);
check_wramx_field(wMapReentryScriptAddress, 1);
check_wramx_field(wTimeCyclesSinceLastCall, 1);
check_wramx_field(wReceiveCallDelay_MinsRemaining, 1);
check_wramx_field(wReceiveCallDelay_StartTime, 1);
check_wramx_field(wBugContestMinsRemaining, 1);
check_wramx_field(wBugContestSecsRemaining, 1);
check_wramx_field(wMapStatusEnd, 1);
// check_wramx_field(wPlayerGender, 1);
// check_wramx_field_mapped(wAge, 1, wd473);
// check_wramx_field_mapped(wPrefecture, 1, wd474);
// check_wramx_field(wd475, 1);
// check_wramx_field(wd476, 1);
// check_wramx_field(wd477, 1);
// check_wramx_field(wd478, 1);
// check_wramx_field(wd479, 1);
// check_wramx_field(wPlayerID, 1);
// check_wramx_field(wPlayerName, 1);
// check_wramx_field(wMomsName, 1);
// check_wramx_field(wRivalName, 1);
// check_wramx_field(wRedsName, 1);
// check_wramx_field(wGreensName, 1);
// check_wramx_field(wSavedAtLeastOnce, 1);
// check_wramx_field(wSpawnAfterChampion, 1);
// check_wramx_field(wStartDay, 1);
// check_wramx_field(wStartHour, 1);
// check_wramx_field(wStartMinute, 1);
// check_wramx_field(wStartSecond, 1);
// check_wramx_field(wRTC, 1);
// check_wramx_field(wDST, 1);
// check_wramx_field(wGameTimeCap, 1);
// check_wramx_field(wGameTimeHours, 1);
// check_wramx_field(wGameTimeMinutes, 1);
// check_wramx_field(wGameTimeSeconds, 1);
// check_wramx_field(wGameTimeFrames, 1);
// check_wramx_field(wCurDay, 1);
// check_wramx_field(wObjectFollow_Leader, 1);
// check_wramx_field(wObjectFollow_Follower, 1);
// check_wramx_field(wCenteredObject, 1);
// check_wramx_field(wFollowerMovementQueueLength, 1);
// check_wramx_field(wFollowMovementQueue, 1);
// check_wramx_field(wPlayerStruct, 1);
// check_wramx_field_mapped(wObjectStruct, 1, wObjectStructs + sizeof(struct Object));
// check_wramx_field(wCmdQueue, 1);
// check_wramx_field(wPlayerObject, 1);
// check_wramx_field_mapped(wMapObject, 1, wMapObjects + sizeof(struct MapObject));
// check_wramx_field(wObjectMasks, 1);
// check_wramx_field(wVariableSprites, 1);
// check_wramx_field(wEnteredMapFromContinue, 1);
// check_wramx_field(wTimeOfDayPal, 1);
// check_wramx_field(wTimeOfDayPalFlags, 1);
// check_wramx_field(wTimeOfDayPalset, 1);
// check_wramx_field(wCurTimeOfDay, 1);
// check_wramx_field(wSecretID, 1);
// check_wramx_field(wStatusFlags, 1);
// check_wramx_field(wStatusFlags2, 1);
// check_wramx_field(wMoney, 1);
// check_wramx_field(wMomsMoney, 1);
// check_wramx_field(wMomSavingMoney, 1);
// check_wramx_field(wCoins, 1);
// check_wramx_field(wJohtoBadges, 1);
// check_wramx_field(wKantoBadges, 1);
// check_wramx_field(wTMsHMs, 1);
// check_wramx_field(wNumItems, 1);
// check_wramx_field(wItems, 1);
// check_wramx_field(wNumKeyItems, 1);
// check_wramx_field(wKeyItems, 1);
// check_wramx_field(wNumBalls, 1);
// check_wramx_field(wBalls, 1);
// check_wramx_field(wNumPCItems, 1);
// check_wramx_field(wPCItems, 1);
// check_wramx_field(wPokegearFlags, 1);
// check_wramx_field(wRadioTuningKnob, 1);
// check_wramx_field(wLastDexMode, 1);
// check_wramx_field(wWhichRegisteredItem, 1);
// check_wramx_field(wRegisteredItem, 1);
// check_wramx_field(wPlayerState, 1);
// check_wramx_field(wHallOfFameCount, 1);
// check_wramx_field(wTradeFlags, 1);
// check_wramx_field(wMooMooBerries, 1);
// check_wramx_field(wUndergroundSwitchPositions, 1);
// check_wramx_field(wFarfetchdPosition, 1);
// check_wramx_field(wPokecenter2FSceneID, 1);
// check_wramx_field(wTradeCenterSceneID, 1);
// check_wramx_field(wColosseumSceneID, 1);
// check_wramx_field(wTimeCapsuleSceneID, 1);
// check_wramx_field(wPowerPlantSceneID, 1);
// check_wramx_field(wCeruleanGymSceneID, 1);
// check_wramx_field(wRoute25SceneID, 1);
// check_wramx_field(wTrainerHouseB1FSceneID, 1);
// check_wramx_field(wVictoryRoadGateSceneID, 1);
// check_wramx_field(wSaffronMagnetTrainStationSceneID, 1);
// check_wramx_field(wRoute16GateSceneID, 1);
// check_wramx_field(wRoute17Route18GateSceneID, 1);
// check_wramx_field(wIndigoPlateauPokecenter1FSceneID, 1);
// check_wramx_field(wWillsRoomSceneID, 1);
// check_wramx_field(wKogasRoomSceneID, 1);
// check_wramx_field(wBrunosRoomSceneID, 1);
// check_wramx_field(wKarensRoomSceneID, 1);
// check_wramx_field(wLancesRoomSceneID, 1);
// check_wramx_field(wHallOfFameSceneID, 1);
// check_wramx_field(wRoute27SceneID, 1);
// check_wramx_field(wNewBarkTownSceneID, 1);
// check_wramx_field(wElmsLabSceneID, 1);
// check_wramx_field(wPlayersHouse1FSceneID, 1);
// check_wramx_field(wRoute29SceneID, 1);
// check_wramx_field(wCherrygroveCitySceneID, 1);
// check_wramx_field(wMrPokemonsHouseSceneID, 1);
// check_wramx_field(wRoute32SceneID, 1);
// check_wramx_field(wRoute35NationalParkGateSceneID, 1);
// check_wramx_field(wRoute36SceneID, 1);
// check_wramx_field(wRoute36NationalParkGateSceneID, 1);
// check_wramx_field(wAzaleaTownSceneID, 1);
// check_wramx_field(wGoldenrodGymSceneID, 1);
// check_wramx_field(wGoldenrodMagnetTrainStationSceneID, 1);
// check_wramx_field(wGoldenrodPokecenter1FSceneID, 1);
// check_wramx_field(wOlivineCitySceneID, 1);
// check_wramx_field(wRoute34SceneID, 1);
// check_wramx_field(wRoute34IlexForestGateSceneID, 1);
// check_wramx_field(wEcruteakTinTowerEntranceSceneID, 1);
// check_wramx_field(wWiseTriosRoomSceneID, 1);
// check_wramx_field(wEcruteakPokecenter1FSceneID, 1);
// check_wramx_field(wEcruteakGymSceneID, 1);
// check_wramx_field(wMahoganyTownSceneID, 1);
// check_wramx_field(wRoute42SceneID, 1);
// check_wramx_field(wCianwoodCitySceneID, 1);
// check_wramx_field(wBattleTower1FSceneID, 1);
// check_wramx_field(wBattleTowerBattleRoomSceneID, 1);
// check_wramx_field(wBattleTowerElevatorSceneID, 1);
// check_wramx_field(wBattleTowerHallwaySceneID, 1);
// check_wramx_field(wBattleTowerOutsideSceneID, 1);
// check_wramx_field(wRoute43GateSceneID, 1);
// check_wramx_field(wMountMoonSceneID, 1);
// check_wramx_field(wSproutTower3FSceneID, 1);
// check_wramx_field(wTinTower1FSceneID, 1);
// check_wramx_field(wBurnedTower1FSceneID, 1);
// check_wramx_field(wBurnedTowerB1FSceneID, 1);
// check_wramx_field(wRadioTower5FSceneID, 1);
// check_wramx_field(wRuinsOfAlphOutsideSceneID, 1);
// check_wramx_field(wRuinsOfAlphResearchCenterSceneID, 1);
// check_wramx_field(wRuinsOfAlphHoOhChamberSceneID, 1);
// check_wramx_field(wRuinsOfAlphKabutoChamberSceneID, 1);
// check_wramx_field(wRuinsOfAlphOmanyteChamberSceneID, 1);
// check_wramx_field(wRuinsOfAlphAerodactylChamberSceneID, 1);
// check_wramx_field(wRuinsOfAlphInnerChamberSceneID, 1);
// check_wramx_field(wMahoganyMart1FSceneID, 1);
// check_wramx_field(wTeamRocketBaseB1FSceneID, 1);
// check_wramx_field(wTeamRocketBaseB2FSceneID, 1);
// check_wramx_field(wTeamRocketBaseB3FSceneID, 1);
// check_wramx_field(wGoldenrodUndergroundSwitchRoomEntrancesSceneID, 1);
// check_wramx_field(wSilverCaveRoom3SceneID, 1);
// check_wramx_field(wVictoryRoadSceneID, 1);
// check_wramx_field(wDragonsDenB1FSceneID, 1);
// check_wramx_field(wDragonShrineSceneID, 1);
// check_wramx_field(wOlivinePortSceneID, 1);
// check_wramx_field(wVermilionPortSceneID, 1);
// check_wramx_field(wFastShip1FSceneID, 1);
// check_wramx_field(wFastShipB1FSceneID, 1);
// check_wramx_field(wMountMoonSquareSceneID, 1);
// check_wramx_field(wMobileTradeRoomSceneID, 1);
// check_wramx_field(wMobileBattleRoomSceneID, 1);
// check_wramx_field(wJackFightCount, 1);
// check_wramx_field(wBeverlyFightCount, 1);
// check_wramx_field(wHueyFightCount, 1);
// check_wramx_field(wGavenFightCount, 1);
// check_wramx_field(wBethFightCount, 1);
// check_wramx_field(wJoseFightCount, 1);
// check_wramx_field(wReenaFightCount, 1);
// check_wramx_field(wJoeyFightCount, 1);
// check_wramx_field(wWadeFightCount, 1);
// check_wramx_field(wRalphFightCount, 1);
// check_wramx_field(wLizFightCount, 1);
// check_wramx_field(wAnthonyFightCount, 1);
// check_wramx_field(wToddFightCount, 1);
// check_wramx_field(wGinaFightCount, 1);
// check_wramx_field(wIrwinFightCount, 1);
// check_wramx_field(wArnieFightCount, 1);
// check_wramx_field(wAlanFightCount, 1);
// check_wramx_field(wDanaFightCount, 1);
// check_wramx_field(wChadFightCount, 1);
// check_wramx_field(wDerekFightCount, 1);
// check_wramx_field(wTullyFightCount, 1);
// check_wramx_field(wBrentFightCount, 1);
// check_wramx_field(wTiffanyFightCount, 1);
// check_wramx_field(wVanceFightCount, 1);
// check_wramx_field(wWiltonFightCount, 1);
// check_wramx_field(wKenjiFightCount, 1);
// check_wramx_field(wParryFightCount, 1);
// check_wramx_field(wErinFightCount, 1);
// check_wramx_field(wEventFlags, 1);
// check_wramx_field(wCurBox, 1);
// check_wramx_field(wBoxNames, 1);
// check_wramx_field(wCelebiEvent, 1);
// check_wramx_field(wBikeFlags, 1);
// check_wramx_field(wCurMapSceneScriptPointer, 1);
// check_wramx_field(wCurCaller, 1);
// check_wramx_field(wCurMapWarpCount, 1);
// check_wramx_field(wCurMapWarpsPointer, 1);
// check_wramx_field(wCurMapCoordEventCount, 1);
// check_wramx_field(wCurMapCoordEventsPointer, 1);
// check_wramx_field(wCurMapBGEventCount, 1);
// check_wramx_field(wCurMapBGEventsPointer, 1);
// check_wramx_field(wCurMapObjectEventCount, 1);
// check_wramx_field(wCurMapObjectEventsPointer, 1);
// check_wramx_field(wCurMapSceneScriptCount, 1);
// check_wramx_field(wCurMapSceneScriptsPointer, 1);
// check_wramx_field(wCurMapCallbackCount, 1);
// check_wramx_field(wCurMapCallbacksPointer, 1);
// check_wramx_field(wDecoBed, 1);
// check_wramx_field(wDecoCarpet, 1);
// check_wramx_field(wDecoPlant, 1);
// check_wramx_field(wDecoPoster, 1);
// check_wramx_field(wDecoConsole, 1);
// check_wramx_field(wDecoLeftOrnament, 1);
// check_wramx_field(wDecoRightOrnament, 1);
// check_wramx_field(wDecoBigDoll, 1);
// check_wramx_field(wWhichMomItem, 1);
// check_wramx_field(wWhichMomItemSet, 1);
// check_wramx_field(wMomItemTriggerBalance, 1);
// check_wramx_field(wDailyResetTimer, 1);
// check_wramx_field(wDailyFlags1, 1);
// check_wramx_field(wDailyFlags2, 1);
// check_wramx_field(wSwarmFlags, 1);
// check_wramx_field(wTimerEventStartDay, 1);
// check_wramx_field(wFruitTreeFlags, 1);
// check_wramx_field(wLuckyNumberDayTimer, 1);
// check_wramx_field(wSpecialPhoneCallID, 1);
// check_wramx_field(wBugContestStartTime, 1);
// check_wramx_field(wUnusedTwoDayTimerOn, 1);
// check_wramx_field(wUnusedTwoDayTimer, 1);
// check_wramx_field(wUnusedTwoDayTimerStartDate, 1);
// check_wramx_field(wMobileOrCable_LastSelection, 1);
// check_wramx_field(wdc41, 1);
// check_wramx_field(wdc42, 1);
// check_wramx_field(wBuenasPassword, 1);
// check_wramx_field(wBlueCardBalance, 1);
// check_wramx_field(wDailyRematchFlags, 1);
// check_wramx_field(wDailyPhoneItemFlags, 1);
// check_wramx_field(wDailyPhoneTimeOfDayFlags, 1);
// check_wramx_field(wKenjiBreakTimer, 1);
// check_wramx_field(wYanmaMapGroup, 1);
// check_wramx_field(wYanmaMapNumber, 1);
// check_wramx_field(wPlayerMonSelection, 1);
// check_wramx_field(wdc5f, 1);
// check_wramx_field(wdc60, 1);
// check_wramx_field(wStepCount, 1);
// check_wramx_field(wPoisonStepCount, 1);
// check_wramx_field(wHappinessStepCount, 1);
// check_wramx_field(wParkBallsRemaining, 1);
// check_wramx_field(wSafariBallsRemaining, 1);
// check_wramx_field(wSafariTimeRemaining, 1);
// check_wramx_field(wPhoneList, 1);
// check_wramx_field(wLuckyNumberShowFlag, 1);
// check_wramx_field(wLuckyIDNumber, 1);
// check_wramx_field(wRepelEffect, 1);
// check_wramx_field(wBikeStep, 1);
// check_wramx_field(wKurtApricornQuantity, 1);
// check_wramx_field(wVisitedSpawns, 1);
// check_wramx_field(wDigWarpNumber, 1);
// check_wramx_field(wDigMapGroup, 1);
// check_wramx_field(wDigMapNumber, 1);
// check_wramx_field(wBackupWarpNumber, 1);
// check_wramx_field(wBackupMapGroup, 1);
// check_wramx_field(wBackupMapNumber, 1);
// check_wramx_field(wLastSpawnMapGroup, 1);
// check_wramx_field(wLastSpawnMapNumber, 1);
// check_wramx_field(wWarpNumber, 1);
// check_wramx_field(wMapGroup, 1);
// check_wramx_field(wMapNumber, 1);
// check_wramx_field(wYCoord, 1);
// check_wramx_field(wXCoord, 1);
// check_wramx_field(wScreenSave, 1);
// section Party
// check_wramx_field(wPartyCount, 1);
// check_wramx_field(wPartySpecies, 1);
// check_wramx_field(wPartyEnd, 1);
// check_wramx_field_mapped(wPartyMon, 1, wPartyMon1);
// check_wramx_field_mapped(wPartyMonOT, 1, wPartyMon1OT);
// check_wramx_field_mapped(wPartyMonNickname, 1, wPartyMon1Nickname);
// check_wramx_field(wPartyMonNicknamesEnd, 1);
// check_wramx_field(wPokedexCaught, 1);
// check_wramx_field(wPokedexSeen, 1);
// check_wramx_field(wUnownDex, 1);
// check_wramx_field(wUnlockedUnowns, 1);
// check_wramx_field(wFirstUnownSeen, 1);
// check_wramx_field(wDayCareMan, 1);
// check_wramx_field(wBreedMon1Nickname, 1);
// check_wramx_field(wBreedMon1OT, 1);
// check_wramx_field(wBreedMon1, 1);
// check_wramx_field(wDayCareLady, 1);
// check_wramx_field(wStepsToEgg, 1);
// check_wramx_field(wBreedMotherOrNonDitto, 1);
// check_wramx_field(wBreedMon2Nickname, 1);
// check_wramx_field(wBreedMon2OT, 1);
// check_wramx_field(wBreedMon2, 1);
// check_wramx_field(wEggMonNickname, 1);
// check_wramx_field(wEggMonOT, 1);
// check_wramx_field(wEggMon, 1);
// check_wramx_field(wBugContestSecondPartySpecies, 1);
// check_wramx_field(wContestMon, 1);
// check_wramx_field(wDunsparceMapGroup, 1);
// check_wramx_field(wDunsparceMapNumber, 1);
// check_wramx_field(wFishingSwarmFlag, 1);
// check_wramx_field(wRoamMon1, 1);
// check_wramx_field(wRoamMon2, 1);
// check_wramx_field(wRoamMon3, 1);
// check_wramx_field(wRoamMons_CurMapNumber, 1);
// check_wramx_field(wRoamMons_CurMapGroup, 1);
// check_wramx_field(wRoamMons_LastMapNumber, 1);
// check_wramx_field(wRoamMons_LastMapGroup, 1);
// check_wramx_field(wBestMagikarpLengthFeet, 1);
// check_wramx_field(wBestMagikarpLengthInches, 1);
// check_wramx_field(wMagikarpRecordHoldersName, 1);
// bank 2
// section Pic Animations
check_wramx_field(wTempTilemap, 2);
check_wramx_field(wPokeAnimSceneIndex, 2);
check_wramx_field(wPokeAnimPointer, 2);
check_wramx_field(wPokeAnimSpecies, 2);
check_wramx_field(wPokeAnimUnownLetter, 2);
check_wramx_field(wPokeAnimSpeciesOrUnown, 2);
check_wramx_field(wPokeAnimGraphicStartTile, 2);
check_wramx_field(wPokeAnimCoord, 2);
check_wramx_field(wPokeAnimFrontpicHeight, 2);
check_wramx_field(wPokeAnimIdleFlag, 2);
check_wramx_field(wPokeAnimSpeed, 2);
check_wramx_field(wPokeAnimPointerBank, 2);
check_wramx_field(wPokeAnimPointerAddr, 2);
check_wramx_field(wPokeAnimFramesBank, 2);
check_wramx_field(wPokeAnimFramesAddr, 2);
check_wramx_field(wPokeAnimBitmaskBank, 2);
check_wramx_field(wPokeAnimBitmaskAddr, 2);
check_wramx_field(wPokeAnimFrame, 2);
check_wramx_field(wPokeAnimJumptableIndex, 2);
check_wramx_field(wPokeAnimRepeatTimer, 2);
check_wramx_field(wPokeAnimCurBitmask, 2);
check_wramx_field(wPokeAnimWaitCounter, 2);
check_wramx_field(wPokeAnimCommand, 2);
check_wramx_field(wPokeAnimParameter, 2);
check_wramx_field(wPokeAnimBitmaskCurCol, 2);
check_wramx_field(wPokeAnimBitmaskCurRow, 2);
check_wramx_field(wPokeAnimBitmaskCurBit, 2);
check_wramx_field(wPokeAnimBitmaskBuffer, 2);
// bank 3
// section Battle Tower RAM
check_wramx_field(w3_d000, 3);
check_wramx_field(w3_d001, 3);
check_wramx_field(w3_d002, 3);
check_wramx_field(w3_d012, 3);
check_wramx_field(w3_d080, 3);
check_wramx_field(w3_d081, 3);
check_wramx_field(w3_d090, 3);
check_wramx_field(wBT_OTTrainer, 3);
check_wramx_field(wBT_TrainerTextIndex, 3);
check_wramx_field(w3_d202, 3);
/// BattleTowerData struct size changed, so these would be off anyway.
// check_wramx_field(w3_d2e2, 3);
// check_wramx_field(w3_d3c2, 3);
// check_wramx_field(w3_d4a2, 3);
// check_wramx_field(w3_d582, 3);
// check_wramx_field(w3_d662, 3);
// check_wramx_field(w3_d742, 3);
check_wramx_field(w3_d800, 3);
check_wramx_field(wBTChoiceOfLvlGroup, 3);
check_wramx_field(w3_d802, 3);
check_wramx_field(w3_d80e, 3);
check_wramx_field(w3_d810, 3);
check_wramx_field(w3_d869, 3);
check_wramx_field(w3_d880, 3);
// check_wramx_field(w3_d881, 3);
// check_wramx_field(w3_d889, 3);
// check_wramx_field(w3_d88a, 3);
check_wramx_field(w3_d88e, 3);
check_wramx_field(w3_d88f, 3);
check_wramx_field(w3_d893, 3);
check_wramx_field(w3_d894, 3);
check_wramx_field(w3_d895, 3);
check_wramx_field(w3_d8a0, 3);
check_wramx_field(w3_d8a1, 3);
check_wramx_field(w3_d8a2, 3);
check_wramx_field(w3_d8a3, 3);
check_wramx_field(w3_dc00, 3);
check_wramx_field(w3_dd68, 3);
check_wramx_field(w3_dfec, 3);
check_wramx_field(w3_dffc, 3);
check_wramx_field(w3_de00, 3);
// bank 4
// bank 5
// section GBC Video
check_wramx_field(wBGPals1, 5);
check_wramx_field(wOBPals1, 5);
check_wramx_field(wBGPals2, 5);
check_wramx_field(wOBPals2, 5);
check_wramx_field(wLYOverrides, 5);
check_wramx_field(wLYOverridesEnd, 5);
check_wramx_field(wMagnetTrainDirection, 5);
check_wramx_field(wMagnetTrainInitPosition, 5);
check_wramx_field(wMagnetTrainHoldPosition, 5);
check_wramx_field(wMagnetTrainFinalPosition, 5);
check_wramx_field(wMagnetTrainPlayerSpriteInitX, 5);
check_wramx_field(wLYOverridesBackup, 5);
// section Battle Animations
check_wramx_field_mapped(legacyBattleAnimTileDictReserved, 5, wBattleAnimTileDict);
check_wramx_field_mapped(legacyBattleAnimObjectsReserved, 5, wAnimObject1);
check_wramx_field_mapped(legacyBattleBGEffectsReserved, 5, wBGEffect1);
check_wramx_field_mapped(legacyLastAnimObjectIndexReserved, 5, wLastAnimObjectIndex);
check_wramx_field_mapped(legacyBattleAnimFlagsReserved, 5, wBattleAnimFlags);
check_wramx_field_mapped(legacyBattleAnimAddressReserved, 5, wBattleAnimAddress);
check_wramx_field_mapped(legacyBattleAnimDelayReserved, 5, wBattleAnimDelay);
check_wramx_field_mapped(legacyBattleAnimParentReserved, 5, wBattleAnimParent);
check_wramx_field_mapped(legacyBattleAnimLoopsReserved, 5, wBattleAnimLoops);
check_wramx_field_mapped(legacyBattleAnimVarReserved, 5, wBattleAnimVar);
check_wramx_field_mapped(legacyBattleAnimByteReserved, 5, wBattleAnimByte);
check_wramx_field_mapped(legacyBattleAnimOAMPointerReserved, 5, wBattleAnimOAMPointerLo);
check_wramx_field(wBattleObjectTempID, 5);
check_wramx_field(wBattleObjectTempXCoord, 5);
check_wramx_field(wBattleObjectTempYCoord, 5);
check_wramx_field(wBattleObjectTempParam, 5);
check_wramx_field(wBattleBGEffectTempID, 5);
check_wramx_field(wBattleBGEffectTempJumptableIndex, 5);
check_wramx_field(wBattleBGEffectTempTurn, 5);
check_wramx_field(wBattleBGEffectTempParam, 5);
check_wramx_field(wBattleAnimTempOAMFlags, 5);
check_wramx_field(wBattleAnimTempFixY, 5);
check_wramx_field(wBattleAnimTempTileID, 5);
check_wramx_field(wBattleAnimTempXCoord, 5);
check_wramx_field(wBattleAnimTempYCoord, 5);
check_wramx_field(wBattleAnimTempXOffset, 5);
check_wramx_field(wBattleAnimTempYOffset, 5);
check_wramx_field(wBattleAnimTempFrameOAMFlags, 5);
check_wramx_field(wBattleAnimTempPalette, 5);
check_wramx_field(wBattleAnimGFXTempPicHeight, 5);
check_wramx_field(wBattleSineWaveTempProgress, 5);
check_wramx_field(wBattleSineWaveTempOffset, 5);
check_wramx_field(wBattleSineWaveTempAmplitude, 5);
check_wramx_field(wBattleSineWaveTempTimer, 5);
check_wramx_field(wBattlePicResizeTempBaseTileID, 5);
check_wramx_field(wBattlePicResizeTempPointer, 5);
check_wramx_field(wSurfWaveBGEffect, 5);
// section Mobile RAM
check_wramx_field(w5_d800, 5);
check_wramx_field(w5_da00, 5);
check_wramx_field(w5_dc00, 5);
check_wramx_field(w5_dc0d, 5);
check_wramx_field(w5_dc11, 5);
check_wramx_field(w5_MobileOpponentBattleMessages, 5);
check_wramx_field(w5_MobileOpponentBattleStartMessage, 5);
check_wramx_field(w5_MobileOpponentBattleWinMessage, 5);
check_wramx_field(w5_MobileOpponentBattleLossMessage, 5);
// bank 6
// section Scratch RAM
check_wramx_field(wScratchTilemap, 6);
check_wramx_field(wScratchAttrmap, 6);
check_wramx_field(wDecompressScratch, 6);
check_wramx_field(wDecompressEnemyFrontpic, 6);
check_wramx_field(w6_d000, 6);
// bank 7
// section Stack RAM
check_wramx_field(wWindowStack, 7);
check_wramx_field(wWindowStackBottom, 7);
