bool IsAPokemon(SpeciesId species);
void DrawBattleHPBar(tile_t* hl, uint8_t d, uint8_t e, uint8_t b, uint8_t c);
void PrepMonFrontpic(tile_t* hl);
void v_PrepMonFrontpic(tile_t* hl);
void PlayStereoCry(SpeciesId species);
void PlayStereoCry2(SpeciesId species);
void PlayMonCry(SpeciesId species);
void PlayMonCry2(SpeciesId species);
void v_PlayMonCry(SpeciesId species);
const struct PokemonCry* LoadCry(SpeciesId species);
int16_t GetCryIndex(SpeciesId species);
void PrintLevel(tile_t* hl, uint8_t lvl);
void PrintLevel_Force3Digits(tile_t* hl, uint8_t a);
void Print8BitNumLeftAlign(tile_t* hl, uint8_t a, uint8_t c);
void GetNthMove(void);
const struct BaseData* GetSpeciesBaseData(SpeciesId species);
bool ConvertBaseDataToLegacy(struct LegacyBaseData* dest, const struct BaseData* src);
bool ConvertBoxMonToNative(struct NativeBoxMon* dest, const struct BoxMon* src);
bool ConvertNativeBoxMonToLegacy(struct BoxMon* dest, const struct NativeBoxMon* src);
bool ConvertPartyMonToNative(struct NativePartyMon* dest, const struct PartyMon* src);
bool ConvertNativePartyMonToLegacy(struct PartyMon* dest, const struct NativePartyMon* src);
void GetBaseData(SpeciesId species);
uint8_t* GetCurNickname(void);
void GetNickname(const uint8_t* hl, uint8_t a);
