void Timer(void);
void UpdateTime(void);
void GetClock(void);
uint8_t FixDays(void);
void FixTime(void);
void InitTimeOfDay(uint8_t hour, uint8_t min);
void InitDayOfWeek(uint8_t day);
void InitTime(uint8_t days, uint8_t hours, uint8_t mins, uint8_t secs);
void ClearClock(void);
void SetClock(void);
void ClearRTCStatus(void);
void RecordRTCStatus(uint8_t a);
uint8_t CheckRTCStatus(void);
