void v_InitScrollingMenu(const struct MenuData* data);
void v_ScrollingMenu(const struct MenuData* data);
// void ScrollingMenu_InitDisplay(const struct MenuData* data);
// u8_flag_s ScrollingMenuJoyAction(const struct MenuData* data);
// uint8_t ScrollingMenu_GetCursorPosition(void);
void ScrollingMenu_ClearLeftColumn(void);
ItemId GetScrollingMenuItemSelection(void);
// void InitScrollingMenuCursor(const struct MenuData* data);
// void ScrollingMenu_InitFlags(const struct MenuData* data);
// void ScrollingMenu_ValidateSwitchItem(void);
// void ScrollingMenu_UpdateDisplay(const struct MenuData* data);
// void ScrollingMenu_CallFunctions1and2(const struct MenuData* data, tile_t* hl);
// void ScrollingMenu_PlaceCursor(const struct MenuData* data);
// void ScrollingMenu_CheckCallFunction3(const struct MenuData* data);
// void ScrollingMenu_GetListItemCoordAndFunctionArgs(const struct MenuData* data, uint8_t a);
