bool AddPhoneNumber(uint8_t c);
bool DelCellNum(uint8_t c);
uint8_t* CheckCellNum(uint8_t c);
uint8_t* Phone_FindOpenSlot(uint8_t c);
uint8_t GetRemainingSpaceInPhoneList(uint8_t c);
void BrokenPlaceFarString(void);
u8_flag_s CheckPhoneCall(void);
// void CheckPhoneContactTimeOfDay(void);
u8_flag_s ChooseRandomCaller(void);
void GetAvailableCallers(void);
bool CheckSpecialPhoneCall(void);
bool SpecialCallOnlyWhenOutside(void);
bool SpecialCallWhereverYouAre(void);
void MakePhoneCallFromPokegear(uint8_t caller);
bool LoadPhoneScriptBank(script_s* s);
bool LoadOutOfAreaScript(script_s* s);
void LoadCallerScript(uint8_t caller);
// void WrongNumber(void);
extern const struct PhoneContact WrongNumber;
bool Script_ReceivePhoneCall(script_s* s);
bool Script_SpecialBillCall(script_s* s);
void Script_SpecialBillCall_LoadBillScript(void);
bool Script_SpecialElmCall(script_s* s);
void Script_SpecialElmCall_LoadElmScript(void);
void RingTwice_StartCall(void);
void PhoneCall(Script_fn_t de);
void Phone_NoSignal(void);
void HangUp(void);
void Phone_CallEnd(void);
void HangUp_ShutDown(void);
void HangUp_Beep(void);
extern const txt_cmd_s PhoneClickText[];
void HangUp_BoopOn(void);
extern const txt_cmd_s PhoneEllipseText[];
void HangUp_BoopOff(void);
void Phone_StartRinging(void);
void HangUp_Wait20Frames(void);
void Phone_Wait20Frames(void);
void Phone_TextboxWithName(uint8_t caller);
void Phone_CallerTextbox(void);
void GetCallerClassAndName(uint8_t* de, uint8_t b);
bool CheckCanDeletePhoneNumber(uint8_t c);
struct LegacyTrainerIdentity GetCallerTrainerClass(uint8_t caller);
void GetCallerName(uint8_t* hl, struct LegacyTrainerIdentity c);
// void Phone_GetTrainerName(void);
// void Phone_GetTrainerClassName(void);
struct CallerLocation GetCallerLocation(void);
bool PhoneOutOfAreaScript(script_s* s);
extern const txt_cmd_s PhoneOutOfAreaText[];
bool PhoneScript_JustTalkToThem(script_s* s);
extern const txt_cmd_s PhoneJustTalkToThemText[];
bool PhoneThankYouTextScript(script_s* s);
extern const txt_cmd_s PhoneThankYouText[];
//#include "data/phone/permanent_numbers.h"
//#include "data/phone/non_trainer_names.h"
//#include "data/phone/phone_contacts.h"
//#include "data/phone/special_calls.h"
extern struct PhoneContact gCallerContact;
