void ExecuteBGEffects(void);
bool QueueBGEffect(void);
// void EndBattleBGEffect(struct BattleBGEffect* bc);
// void DoBattleBGEffectFunction(struct BattleBGEffect* bc);
// void BattleBGEffects(void);
extern void(*const BattleBGEffects[54])(struct BattleBGEffect*);
// void BattleBGEffect_End(struct BattleBGEffect* bc);
void BatttleBGEffects_GetNamedJumptablePointer(void);
void BattleBGEffects_AnonJumptable(void);
// void BattleBGEffects_IncAnonJumptableIndex(void);
// void BattleBGEffect_FlashInverted(struct BattleBGEffect* bc);
// void BattleBGEffect_FlashWhite(struct BattleBGEffect* bc);
// void BattleBGEffect_FlashContinue(struct BattleBGEffect* bc, const uint8_t* de);
// void BattleBGEffect_WhiteHues(struct BattleBGEffect* bc);
// void BattleBGEffect_BlackHues(struct BattleBGEffect* bc);
// void BattleBGEffect_AlternateHues(struct BattleBGEffect* bc);
// void BattleBGEffect_CycleOBPalsGrayAndYellow(struct BattleBGEffect* bc);
// void BattleBGEffect_CycleMidOBPalsGrayAndYellow(struct BattleBGEffect* bc);
// void BattleBGEffect_CycleBGPals_Inverted(struct BattleBGEffect* bc);
// void BattleBGEffect_HideMon(struct BattleBGEffect* bc);
// void BattleBGEffect_ShowMon(struct BattleBGEffect* bc);
// void BattleBGEffect_BattlerObj_1Row(struct BattleBGEffect* bc);
// void BattleBGEffect_BattlerObj_2Row(struct BattleBGEffect* bc);
void v_QueueBattleAnimation(void);
// void BattleBGEffect_RemoveMon(struct BattleBGEffect* bc);
// void BattleBGEffect_EnterMon(struct BattleBGEffect* bc);
// void BattleBGEffect_ReturnMon(struct BattleBGEffect* bc);
// void BattleBGEffect_Surf(struct BattleBGEffect* bc);
// void BattleBGEffect_Whirlpool(struct BattleBGEffect* bc);
// void BattleBGEffect_StartWater(struct BattleBGEffect* bc);
// void BattleBGEffect_Water(struct BattleBGEffect* bc);
// void BattleBGEffect_EndWater(struct BattleBGEffect* bc);
// void BattleBGEffect_Psychic(struct BattleBGEffect* bc);
// void BattleBGEffect_Teleport(struct BattleBGEffect* bc);
// void BattleBGEffect_NightShade(struct BattleBGEffect* bc);
// void BattleBGEffect_DoubleTeam(struct BattleBGEffect* bc);
// void BattleBGEffect_AcidArmor(struct BattleBGEffect* bc);
// void BattleBGEffect_Withdraw(struct BattleBGEffect* bc);
// void BattleBGEffect_Dig(struct BattleBGEffect* bc);
// void BattleBGEffect_Tackle(struct BattleBGEffect* bc);
// void BattleBGEffect_BodySlam(struct BattleBGEffect* bc);
// void Tackle_MoveForward(struct BattleBGEffect* bc);
// void Tackle_ReturnMove(struct BattleBGEffect* bc);
// void Rollout_FillLYOverridesBackup(uint8_t a);
// void BattleBGEffect_BetaPursuit(struct BattleBGEffect* bc);
// void VitalThrow_MoveBackwards(struct BattleBGEffect* bc);
// void BattleBGEffect_VitalThrow(struct BattleBGEffect* bc);
// void BattleBGEffect_WobbleMon(struct BattleBGEffect* bc);
// void BattleBGEffect_Flail(struct BattleBGEffect* bc);
// void BattleBGEffect_WaveDeformMon(struct BattleBGEffect* bc);
// void BattleBGEffect_BounceDown(struct BattleBGEffect* bc);
void BattleBGEffect_BetaSendOutMon1(void);
void BattleBGEffect_BetaSendOutMon2(void);
// void BattleBGEffect_FadeMonsToBlackRepeating(void);
// void BattleBGEffect_RapidFlash(struct BattleBGEffect* bc);
// void BattleBGEffect_FadeMonToLight(struct BattleBGEffect* bc);
// void BattleBGEffect_FadeMonToBlack(struct BattleBGEffect* bc);
// void BattleBGEffect_FadeMonToLightRepeating(struct BattleBGEffect* bc);
// void BattleBGEffect_FadeMonToBlackRepeating(struct BattleBGEffect* bc);
// void BattleBGEffect_CycleMonLightDarkRepeating(struct BattleBGEffect* bc);
// void BattleBGEffect_FlashMonRepeating(struct BattleBGEffect* bc);
// void BattleBGEffect_FadeMonToWhiteWaitFadeBack(struct BattleBGEffect* bc);
// void BattleBGEffect_FadeMonFromWhite(struct BattleBGEffect* bc);
// void BattleBGEffect_VibrateMon(struct BattleBGEffect* bc);
// void BattleBGEffect_WobblePlayer(struct BattleBGEffect* bc);
// void BattleBGEffect_Rollout(struct BattleBGEffect* bc);
// void BattleBGEffect_ShakeScreenX(struct BattleBGEffect* bc);
// void BattleBGEffect_ShakeScreenY(struct BattleBGEffect* bc);
// u8_flag_s BattleBGEffects_GetShakeAmount(struct BattleBGEffect* bc);
// void BattleBGEffect_WobbleScreen(struct BattleBGEffect* bc);
// u8_flag_s BattleBGEffect_GetNthDMGPal(struct BattleBGEffect* bc, const uint8_t* de);
// void BGEffect_RapidCyclePals(struct BattleBGEffect* bc, const uint8_t* de);
// void BGEffects_LoadBGPal0_OBPal1(uint8_t a);
// void BGEffects_LoadBGPal1_OBPal0(uint8_t a);
// u8_flag_s BattleBGEffect_GetFirstDMGPal(struct BattleBGEffect* bc, const uint8_t* de);
// u8_flag_s BattleBGEffect_GetNextDMGPal(struct BattleBGEffect* bc, const uint8_t* de, uint8_t a);
// void BattleBGEffects_ClearLYOverrides(void);
// void BattleBGEffects_SetLYOverrides(uint8_t a);
// void BattleBGEffect_SetLCDStatCustoms1(struct BattleBGEffect* bc, uint8_t a);
// void BattleBGEffect_SetLCDStatCustoms2(struct BattleBGEffect* bc, uint8_t a);
// void BattleAnim_ResetLCDStatCustom(struct BattleBGEffect* bc);
void BattleBGEffects_ResetVideoHRAM(void);
// void DeformScreen(uint8_t d, uint8_t e);
// void InitSurfWaves(uint8_t d, uint8_t e);
// void DeformWater(uint8_t d, uint8_t e, uint8_t a);
// void BattleBGEffect_WavyScreenFX(void);
// void BGEffect_FillLYOverridesBackup(uint8_t a);
// void BGEffect_DisplaceLYOverridesBackup(uint8_t a);
// uint8_t BGEffect_CheckBattleTurn(struct BattleBGEffect* bc);
// bool BGEffect_CheckFlyDigStatus(struct BattleBGEffect* bc);
// bool BattleBGEffects_CheckSGB(void);
uint8_t BattleBGEffects_Sine(uint8_t e, uint8_t d);
uint8_t BattleBGEffects_Cosine(uint8_t e, uint8_t d);
