bool v_ReceiveItem(item_pocket_u* pocket, ItemId a, uint8_t count);
bool v_TossItem(item_pocket_u* pocket, ItemId item, uint8_t count);
bool v_CheckItem(item_pocket_u* hl, ItemId item);
// void DoesHLEqualNumItems(void);
uint8_t GetPocketCapacity(item_quantity_pocket_s* pocket);
bool PutItemInPocket(item_quantity_pocket_s* pocket, ItemId item, uint8_t count);
bool RemoveItemFromPocket(item_quantity_pocket_s* hl, ItemId item, uint8_t count);
bool CheckTheItem(item_quantity_pocket_s* pocket, ItemId item);
bool ReceiveKeyItem(ItemId item);
bool TossKeyItem(ItemId item, uint8_t index);
bool CheckKeyItems(ItemId c);
bool ReceiveTMHM(uint8_t id, uint8_t count);
bool TossTMHM(uint8_t tmhm, uint8_t count);
bool CheckTMHM(uint8_t c);
uint8_t GetTMHMNumber(ItemId c);
ItemId GetNumberedTMHM(uint8_t tmhm);
bool v_CheckTossableItem(ItemId item);
bool CheckSelectableItem(ItemId item);
uint8_t CheckItemPocket(ItemId item);
uint8_t CheckItemContext(ItemId item);
uint8_t CheckItemMenu(ItemId item);
// void GetItemAttr(void);
void ItemAttr_ReturnCarry(void);
uint16_t GetItemPrice(ItemId item);
