void Pack(void);
void Pack_RunJumptable(void);
extern const struct MenuHeader MenuHeader_UsableKeyItem;
extern void (*const Jumptable_UseGiveTossRegisterQuit[])(void);
extern const struct MenuHeader MenuHeader_UsableItem;
extern void (*const Jumptable_UseGiveTossQuit[])(void);
extern const struct MenuHeader MenuHeader_UnusableItem;
extern void (*const Jumptable_UseQuit[])(void);
extern const struct MenuHeader MenuHeader_UnusableKeyItem;
extern void (*const Jumptable_UseRegisterQuit[])(void);
extern const struct MenuHeader MenuHeader_HoldableKeyItem;
extern void (*const Jumptable_GiveTossRegisterQuit[])(void);
extern const struct MenuHeader MenuHeader_HoldableItem;
extern void (*const Jumptable_GiveTossQuit[])(void);
void UseItem(void);
void TossMenu(void);
void ResetPocketCursorPositions(void);
void RegisterItem(void);
void GiveItem(void);
void QuitItemSubmenu(void);
void BattlePack(void);
void ItemSubmenu(void);
void TMHMSubmenu(uint8_t a);
void InitPackBuffers(void);
void DepositSellInitPackBuffers(void);
void DepositSellPack(void);
void InitPocket(uint8_t pocket);
bool DepositSellTutorial_InterpretJoypad(void);
void TutorialPack(void);
void Pack_JumptableNext(void);
void Pack_GetJumptablePointer(void);
void Pack_QuitNoScript(void);
void Pack_QuitRunScript(void);
void Pack_PrintTextNoScroll(const txt_cmd_s* hl);
void WaitBGMap_DrawPackGFX(void);
void DrawPackGFX(uint8_t pocket);
extern const uint16_t PackGFXPointers[];
bool Pack_InterpretJoypad(uint8_t b, uint8_t c);
void Pack_InitGFX(void);
void PlacePackGFX(void);
void DrawPocketName(uint8_t pocket);
void Pack_GetItemName(ItemId item);
void Pack_ClearTilemap(void);
void ClearPocketList(void);
void Pack_InitColors(void);
extern const struct MenuHeader ItemsPocketMenuHeader;
extern const struct MenuHeader PC_Mart_ItemsPocketMenuHeader;
extern const struct MenuHeader KeyItemsPocketMenuHeader;
extern const struct MenuHeader PC_Mart_KeyItemsPocketMenuHeader;
extern const struct MenuHeader BallsPocketMenuHeader;
extern const struct MenuHeader PC_Mart_BallsPocketMenuHeader;
extern const txt_cmd_s PackNoItemText[];
extern const txt_cmd_s AskThrowAwayText[];
extern const txt_cmd_s AskQuantityThrowAwayText[];
extern const txt_cmd_s ThrewAwayText[];
extern const txt_cmd_s OakThisIsntTheTimeText[];
extern const txt_cmd_s YouDontHaveAMonText[];
extern const txt_cmd_s RegisteredItemText[];
extern const txt_cmd_s CantRegisterText[];
extern const txt_cmd_s AskItemMoveText[];
extern const txt_cmd_s PackEmptyText[];
extern const txt_cmd_s YouCantUseItInABattleText[];
extern const char PackMenuGFX[];
extern const char PackGFX[];
//#include "gfx/pack/pack_menu.tilemap"
//#include "gfx/pack/pack_menu.2bpp"
//#include "gfx/pack/pack.2bpp"
