bool TMHMPocket(void);
void ConvertCurItemIntoCurTMHM(void);
move_t GetTMHMItemMove(ItemId item);
bool AskTeachTMHM(void);
u8_flag_s ChooseMonToLearnTMHM(void);
u8_flag_s ChooseMonToLearnTMHM_NoRefresh(void);
void TeachTMHM(void);
extern const txt_cmd_s BootedTMText[];
extern const txt_cmd_s BootedHMText[];
extern const txt_cmd_s ContainedMoveText[];
extern const txt_cmd_s TMHMNotCompatibleText[];
bool TMHM_PocketLoop(void);
void TMHM_JoypadLoop(void);
void TMHM_ShowTMMoveDescription(void);
bool TMHM_ChooseTMorHM(void);
bool TMHM_CheckHoveringOverCancel(void);
bool TMHM_ExitPack(void);
bool v_TMHM_ExitPack(void);
bool TMHM_ExitPocket(void);
void TMHM_ScrollPocket(void);
uint8_t TMHM_DisplayPocketItems(void);
uint8_t* TMHMPocket_GetCurrentLineCoord(uint8_t d);
// void PlaceMoveNameAfterTMHMName(void);
extern const char TMHM_CancelString[];
uint8_t TMHM_GetCurrentPocketPosition(void);
uint8_t Tutorial_TMHMPocket(void);
void TMHM_PlaySFX_ReadText2(void);
void VerboseReceiveTMHM(void);
void ConsumeTM(void);
void CountTMsHMs(void);
