void EvolvePokemon(void);
void EvolveAfterBattle(void);
void EvolveAfterBattle_MasterLoop(void);
void UpdateSpeciesNameIfNotNicknamed(void);
void CancelEvolution(void);
bool IsMonHoldingEverstone(void);
extern const txt_cmd_s CongratulationsYourPokemonText[];
extern const txt_cmd_s EvolvedIntoText[];
extern const txt_cmd_s StoppedEvolvingText[];
extern const txt_cmd_s EvolvingText[];
void LearnLevelMoves(struct PartyMon* mon, uint8_t level, species_t species);
void FillMoves(move_t* de, uint8_t* pp, species_t species, uint8_t level);
void FillNativeMoves(MoveId* dest, uint8_t* pp, SpeciesId species, uint8_t level);
void ShiftMoves(move_t* hl);
void ShiftNativeMoves(MoveId* moves);
uint8_t EvoFlagAction(uint8_t* hl, uint8_t c, uint8_t b);
species_t GetPreEvolution(species_t species);
SpeciesId GetPreEvolutionNative(SpeciesId species);
