bool HasNoItems(void);
bool TossItemFromPC(item_pocket_u* de);
void CantUseItem(void);
extern const txt_cmd_s ItemsOakWarningText[];
void PartyMonItemName(ItemId item);
u8_pair_s CancelPokemonAction(void);
u8_pair_s PokemonActionSubmenu(void);
u8_pair_s SwitchPartyMons(void);
u8_pair_s GiveTakePartyMonItem(void);
void TryGiveItemToPartymon(void);
void GivePartyItem(item_t item);
void TakePartyItem(void);
extern const struct MenuHeader GiveTakeItemMenuData;
extern const txt_cmd_s PokemonSwapItemText[];
extern const txt_cmd_s PokemonHoldItemText[];
extern const txt_cmd_s PokemonRemoveMailText[];
extern const txt_cmd_s PokemonNotHoldingText[];
extern const txt_cmd_s ItemStorageFullText[];
extern const txt_cmd_s PokemonTookItemText[];
extern const txt_cmd_s PokemonAskSwapItemText[];
extern const txt_cmd_s ItemCantHeldText[];
item_t* GetPartyItemLocation(void);
bool ReceiveItemFromPokemon(item_t item);
void GiveItemToPokemon(item_t item);
bool StartMenuYesNo(const struct TextCmd* hl);
void ComposeMailMessage(void);
u8_pair_s MonMailAction(void);
u8_pair_s OpenPartyStats(void);
u8_pair_s MonMenu_Cut(void);
u8_pair_s MonMenu_Fly(void);
u8_pair_s MonMenu_Flash(void);
u8_pair_s MonMenu_Strength(void);
u8_pair_s MonMenu_Whirlpool(void);
u8_pair_s MonMenu_Waterfall(void);
u8_pair_s MonMenu_Teleport(void);
u8_pair_s MonMenu_Surf(void);
u8_pair_s MonMenu_Dig(void);
u8_pair_s MonMenu_Softboiled_MilkDrink(void);
u8_pair_s MonMenu_Headbutt(void);
u8_pair_s MonMenu_RockSmash(void);
u8_pair_s MonMenu_SweetScent(void);
u8_flag_s ChooseMoveToDelete(void);
extern const uint8_t DeleteMoveScreen2DMenuData[];
u8_pair_s ManagePokemonMoves(void);
void MoveScreenLoop(void);
extern const uint8_t MoveScreen2DMenuData[];
extern const char String_MoveWhere[];
void SetUpMoveScreenBG(void);
void SetUpMoveList(void);
void PrepareToPlaceMoveData(void);
void PlaceMoveData(void);
extern const char String_MoveType_Top[];
extern const char String_MoveType_Bottom[];
extern const char String_MoveAtk[];
extern const char String_MoveNoPower[];
void PlaceMoveScreenArrows(void);
void PlaceMoveScreenLeftArrow(void);
void PlaceMoveScreenRightArrow(void);
